/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package itp.project.x.Interfaces;


import DBConnect.DBconnect;
import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/**
 *
 * @author Asus
 */
public class signup extends javax.swing.JFrame {

    Connection con=null;
    PreparedStatement pst=null;
    
    public signup() {
        initComponents();
        
        con = DBconnect.connect();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        uname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        typeBox = new javax.swing.JComboBox<>();
        pwd2 = new javax.swing.JPasswordField();
        jButton5 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        pwd1 = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setText("Back");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(1260, 10, 104, 34);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("User Name");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(650, 230, 180, 40);

        uname.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(uname);
        uname.setBounds(830, 230, 270, 40);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Confirm Password");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(650, 360, 180, 40);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Email Address");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(650, 430, 180, 40);

        email.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(email);
        email.setBounds(830, 430, 270, 40);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Wellcome To Signup Page");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(420, 60, 400, 42);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Access Type");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(650, 510, 180, 40);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setText("Signup");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(840, 650, 104, 40);

        typeBox.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        typeBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "User", "Admin" }));
        getContentPane().add(typeBox);
        typeBox.setBounds(840, 520, 150, 40);

        pwd2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(pwd2);
        pwd2.setBounds(830, 360, 270, 40);

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton5.setText("Login");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(980, 650, 104, 40);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Create Password");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(650, 290, 180, 40);

        pwd1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(pwd1);
        pwd1.setBounds(830, 290, 270, 40);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/itp/project/x/Interfaces/images/Signup.jpg"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 1370, 770);

        setSize(new java.awt.Dimension(1387, 807));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
        
        
        // send data to DB
        
        String username= uname.getText();
        String password=pwd2.getText();
        String emailAdd=email.getText();
        String type=typeBox.getSelectedItem().toString();

        try{
        String q="INSERT INTO login(username,password,accesslevel,email)values ('"+username+"','"+password+"','"+type+"','"+emailAdd+"')";
        
        pst=con.prepareStatement(q);
        pst.execute();
        
        JOptionPane.showMessageDialog (null, "Signup Is Successful", "Title", JOptionPane.INFORMATION_MESSAGE);
        
        }
         catch(Exception e)
        {
            JOptionPane.showMessageDialog(this,"Cannot add this person");
            System.out.println(e);
        }
        // clear text feield
        uname.setText("");
        pwd2.setText("");
        email.setText("");
        
        /*  Redirect to Product Lookup page
        
        Product_Lookup prolk =new Product_Lookup();
        prolk.setVisible(true);
        this.dispose();
        */
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        //  Redirect to login page
        
        login lg =new login();
        lg.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
      
        
//  Redirect to login page
        
        login lg =new login();
        lg.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new signup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField email;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPasswordField pwd1;
    private javax.swing.JPasswordField pwd2;
    private javax.swing.JComboBox<String> typeBox;
    private javax.swing.JTextField uname;
    // End of variables declaration//GEN-END:variables
}
