package bill;


import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;
import java.sql.SQLException;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.DriverManager;
import java.util.ArrayList;
import javax.swing.table.TableModel;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author DELL
 */

public class BillEdit extends javax.swing.JFrame {
 
    Connection con = null;
    PreparedStatement pst=null ;
    ResultSet rs = null;
   
    /**
     * Creates new form BillEdit
     */
    public BillEdit() {
        initComponents();
        con = DBconnect.connect();
        tableload();
        //show_value_in_Jtable();
    }
    
    public void tableload()
    {
        try
        {
         String sql= "SELECT BillId,InvoiceId,item_code,item-Name,QTY,bill_Date,MRP,Discounts_Allowed,Net_Amount FROM bill";
         pst = con.prepareStatement(sql);
         rs = pst.executeQuery();
         
         jTable2.setModel(DbUtils.resultSetToTableModel(rs));
        }
        
        catch(Exception e)
        {
        
        }
    }

    
    
    ///update delete
    
    
     public Connection getConnection()
    {
        Connection con = null;
         try {
            Class.forName("com.mysql.jdbc.Driver");
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/buisnessmanagementsystem","root","");
             return con;
        } catch (Exception e) {
            System.out.println(e);
            e.printStackTrace();
            return null;
        }
          
    }
    
   /* public ArrayList<billInsert> getUserList()
    {
        ArrayList<billInsert> UserList=new ArrayList<billInsert>();
        Connection connect=getConnection();
        String qry ="SELECT * FROM  `bill` ";
        ResultSet rs ;
        Statement st;
        
        try{
            st=connect.createStatement();
            rs=st.executeQuery(qry);
            billInsert bill1;
            
            while(rs.next())
            {
                //bill1 =new billInsert (rs.getString("InvoiceId"),rs.getString("Item_Code"),rs.getString("Item_Name"),rs.getFloat("QTY"),rs.getString("bill_Date"),rs.getFloat("MRP"),rs.getFloat("DiscountsP"),rs.getFloat("Discounts_Allowed"),rs.getFloat("Net_Amount"));
                //UserList.add(bill1);
            }
        }
          catch(Exception e)
                    {
                        e.printStackTrace();
                    }
        return UserList;
    }
     
     */
    
    //display data in Jtable
    
    /*public void show_value_in_Jtable()
    {
        ArrayList<billInsert> list=getUserList();
        DefaultTableModel model=(DefaultTableModel)jTable2.getModel();
        Object[] row=new Object[9];
        for(int i=0;i<list.size();i++)
        {
            row[0]=list.get(i).getInvoiceId();
            row[1]=list.get(i).getItemCode();
            row[2]=list.get(i).getItemName();
            row[3]=list.get(i).getQuantity();
            row[4]=list.get(i).getDate();
            row[5]=list.get(i).getMrp();
            row[6]=list.get(i).getDiscount();
            row[7]=list.get(i).getDiscount_allowed();
            row[8]=list.get(i).getNetprice();
            
            model.addRow(row);
        }
    }
    
    //Execute the sql query
    public void executeQuery(String qry1)
    {
        Connection con = null;
        Statement st;
        
        try{
            st=con.createStatement();
            if((st.executeUpdate(qry1))== 1)
            {
               JOptionPane.showConfirmDialog(null,"Do update"); 
            }
            else
            {
                JOptionPane.showConfirmDialog(null,"erro?");
            }
        }
        
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
    }
     */
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jTextField6 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1366, 768));
        setMinimumSize(new java.awt.Dimension(1366, 768));
        setPreferredSize(new java.awt.Dimension(1366, 768));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
        });
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 134, 30));
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 134, 30));
        jPanel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, 134, 30));

        jTextField4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField4KeyPressed(evt);
            }
        });
        jPanel1.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 320, 134, 30));

        jTextField5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField5KeyPressed(evt);
            }
        });
        jPanel1.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 380, 134, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Item code");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Item Name");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Quantity");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Discount");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 390, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Price");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 450, -1, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Delete");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 600, 130, 36));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("Reset");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 600, 130, 36));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setText("Edit");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton3MouseReleased(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 600, 130, 30));

        jTextField6.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                jTextField6InputMethodTextChanged(evt);
            }
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        jTextField6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField6KeyPressed(evt);
            }
        });
        jPanel1.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 450, 134, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("MRP");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 520, -1, -1));

        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        jTextField7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField7KeyPressed(evt);
            }
        });
        jPanel1.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 510, 134, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Date");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 590, -1, -1));

        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 580, 134, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Discounts Allowed");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 650, -1, -1));
        jPanel1.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 650, 134, 30));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "PayedId", "Invoice Id", "ItemCode", "ItemName", "Quantity", "Billdate", "MRP", "Discount", "discountAllowed", "NetPrice"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTable2MouseEntered(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);
        if (jTable2.getColumnModel().getColumnCount() > 0) {
            jTable2.getColumnModel().getColumn(0).setResizable(false);
            jTable2.getColumnModel().getColumn(1).setResizable(false);
            jTable2.getColumnModel().getColumn(2).setResizable(false);
            jTable2.getColumnModel().getColumn(3).setResizable(false);
            jTable2.getColumnModel().getColumn(4).setResizable(false);
            jTable2.getColumnModel().getColumn(5).setResizable(false);
            jTable2.getColumnModel().getColumn(6).setResizable(false);
            jTable2.getColumnModel().getColumn(7).setResizable(false);
            jTable2.getColumnModel().getColumn(8).setResizable(false);
            jTable2.getColumnModel().getColumn(9).setResizable(false);
        }

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 90, 879, 490));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("InvoiceNo");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("PayedId");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, -1, -1));

        jTextField10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField10ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 134, 30));

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton5.setText("Back");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 40, 120, 30));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/backgrnd1.png"))); // NOI18N
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 770));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 770));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         int x =JOptionPane.showConfirmDialog(null,"Do You Delete This?");
        
        
        if(x==0){
        String billId=jTextField10.getText();    
        String invoiceid=jTextField1.getText();    
        String itemCode=jTextField2.getText();
        String itemName=jTextField3.getText();
        String quty=jTextField4.getText(); 
        String discount=jTextField5.getText();
        String netPrice=jTextField6.getText();
        String mrp=jTextField7.getText();
        String date=jTextField8.getText();
        String discountAllowed=jTextField9.getText();
      
        
        
         
           String sql ="DELETE from bill where BillId = "+billId+" ";
          
            try
            {
            pst=con.prepareStatement(sql);
            pst.execute(); 
            JOptionPane.showMessageDialog(null, "Deleted");
               tableload();
               }
            catch(Exception e)
            {
            JOptionPane.showMessageDialog(null, e);
            e.printStackTrace();
            }
        
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jTextField2.setText(null);
        jTextField3.setText(null);
        jTextField4.setText(null);
        jTextField5.setText(null);
        jTextField1.setText(null);
        jTextField6.setText(null);
        jTextField7.setText(null);
        jTextField8.setText(null);
        jTextField9.setText(null);
        jTextField10.setText(null);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
        // TODO add your handling code here:
       
        String InvoiceId=jTextField1.getText();
        
  
           try{
         String sql="select Bill_ID,InvoiceId,item_Code,Item_Name,QTY,bill_Date,MRP,DiscountsP,Discounts_Allowed,Net_Amount  from bill where InvoiceId='"+ jTextField1.getText() +"'";//search name   
          pst=con.prepareStatement(sql);
           
            ResultSet rs = pst.executeQuery();
            jTable2.setModel(DbUtils.resultSetToTableModel(rs));
           
           
            
            if(rs.next())
            {
                String billId=rs.getString("BillId");//get value
                jTextField10.setText(billId);
                String itemCode=rs.getString("item_Code");//get value
                jTextField2.setText(itemCode);//set value
                String ItemName=rs.getString("Item_Name");
                jTextField3.setText(ItemName);
                String Quantity=rs.getString("QTY");
                jTextField4.setText(Quantity);
                String Discount=rs.getString("DiscountsP");
                jTextField5.setText(Discount);
                String NetPrice=rs.getString("Net_Amount");
                jTextField6.setText(NetPrice);
                String MRP=rs.getString("MRP");
                jTextField7.setText(MRP);
                String date=rs.getString("bill_Date");
                jTextField8.setText(date);
                String discountAllowed=rs.getString("Discounts_Allowed");
                jTextField9.setText(date);
                
            }
        }
        
         catch(Exception e){
        JOptionPane.showMessageDialog(null, "Invoice ID not valid");
        e.printStackTrace();
        }
           
        
       /* try
        {
         String sql="select BillId,item_Code,Item_Name,QTY,bill_Date,MRP,DiscountsP,Discounts_Allowed,Net_Amount  from bill where InvoiceId='"+jTextField1.getText()+"'";//search name   
         pst=con.prepareStatement(sql);
         rs = pst.executeQuery();
         jTable2.setModel(DbUtils.resultSetToTableModel(rs));
         
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
        */
       /*
        String sql="select itemCode,ItemName,Quantity,Discount,NetPrice  from billing where invoiceId='"+jTextField1.getText()+"'";//search name
            pst=con.prepareStatement(sql);
           
            ResultSet rs = pst.executeQuery();
        */
          
          
    }//GEN-LAST:event_jTextField1KeyPressed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
          int Y = JOptionPane.showConfirmDialog(null, "Do You Want Update?");
          if(Y==0){
            String billId=jTextField10.getText();
            String id=jTextField1.getText();
            String itemcode=jTextField2.getText();
            String name =jTextField3.getText();
            String quantity = jTextField4.getText();
            String discount=jTextField5.getText();
            String salePrice=jTextField7.getText();
            String netPrice=jTextField6.getText();
            String date=jTextField8.getText();
            String discountAllowed=jTextField9.getText();
            
            String sql2="UPDATE bill SET  item_Code='"+itemcode+"',Item_Name='"+name+"',QTY="+quantity+",bill_Date='"+date+"',MRP="+salePrice+",DiscountsP="+ discount+",Discounts_Allowed="+discountAllowed+",Net_Amount="+netPrice+"  where InvoiceId="+id+" ";
             try
            {
            pst=con.prepareStatement(sql2);
            pst.execute(); 
              JOptionPane.showMessageDialog(null, "Updated");
            tableload();
            
            //JOptionPane.showMessageDialog(null, "Updated"); 
            //load table
            
            
            }
            catch(Exception e)
            {
            //JOptionPane.showMessageDialog(null, e);    
            e.printStackTrace();
            }
             
             //tableload();
            
        }
          tableload();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        // TODO add your handling code here:
        /*
        int r= jTable2.getSelectedRow();
        TableModel model=jTable2.getModel();
        String billId=jTable2.getValueAt(r,0).toString();
        String id= jTable2.getValueAt(r,1).toString();
        String itemcode= jTable2.getValueAt(r,2).toString();
        String name= jTable2.getValueAt(r,3).toString();
        String quantity= jTable2.getValueAt(r,4).toString();
        String date= jTable2.getValueAt(r,5).toString();
        String salePrice= jTable2.getValueAt(r,6).toString();
        String discount= jTable2.getValueAt(r,7).toString();
        String netPrice= jTable2.getValueAt(r,9).toString();
        String discountAllowed= jTable2.getValueAt(r,8).toString();
       
        jTextField10.setText(billId);
        jTextField1.setText(id);
        jTextField2.setText(itemcode);
        jTextField3.setText(name);
        jTextField4.setText(quantity);
        jTextField8.setText(date);
        jTextField7.setText(salePrice);
        jTextField6.setText(netPrice);
        jTextField5.setText(discount);
        jTextField9.setText(discountAllowed);
        
        */
        
        
           int r= jTable2.getSelectedRow();
        //String creditId= jTable2.getValueAt(r,0).toString();
        String PayId= jTable2.getValueAt(r,0).toString();
        String invoiceId= jTable2.getValueAt(r,1).toString();       
        String ItemCode= jTable2.getValueAt(r,2).toString();
        String ItemName= jTable2.getValueAt(r,3).toString();
        String quantity= jTable2.getValueAt(r,4).toString();
         String date= jTable2.getValueAt(r,5).toString(); 
        String MRP= jTable2.getValueAt(r,6).toString();
        String discount= jTable2.getValueAt(r,7).toString();
        String discountAllowed= jTable2.getValueAt(r,8).toString();       
        String netprice= jTable2.getValueAt(r,9).toString();
   
        
       //jTextField6.setText(creditId);
        
       jTextField10.setText(PayId);
       jTextField2.setText(ItemCode);
       jTextField3.setText( ItemName);
       jTextField4.setText(quantity);
       jTextField5.setText(discount);
       jTextField6.setText(netprice);
       jTextField7.setText(MRP);      
       jTextField8.setText(date);
       jTextField9.setText(discountAllowed);
     
     
    }//GEN-LAST:event_jTable2MouseClicked

    private void jTextField10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField10ActionPerformed

    private void jTextField7KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField7KeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTextField7KeyPressed

    private void jTextField6KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField6KeyPressed
        // TODO add your handling code here:
        
        
                int f=0;   
    String s1=jTextField6.getText();
    String s2=null;
    for(int i=0;i<s1.length();i++)
    {
      char a=s1.charAt(i);  
       
      if(Character.isLetter(a))
      {
           f=1;
        s1=s1.substring(0, i);   
      }
    }
    if(f==1)
    {
        JOptionPane.showMessageDialog(null,"character not allowed");
        jTextField6.setText(null);
    }
        Float saleAmount1;
        Float quty1;
        Float discount1;
        
       //Float Sum=0f;

        //saleAmount1=Float.parseFloat(jTextField2.getText());
        //quty1=Float.parseFloat(jTextField6.getText());
        //discount1=Float.parseFloat(jTextField8.getText());
        
        Pay1 p = new Pay1();
        p.setSaleAmount1(Float.parseFloat(jTextField7.getText()));
        p.setDiscount1(Float.parseFloat(jTextField5.getText()));
        p.setQuty1(Float.parseFloat(jTextField4.getText()));

        Double total = p.cal();
        jTextField6.setText(String.valueOf(total));
        double discount=p.cal2();
        jTextField9.setText(String.valueOf(discount));
        
        
       /* String code = jTextField1.getText();
        String itemName = jTextField3.getText();
        String quty = jTextField6.getText();
        String Discount = jTextField8.getText();
        String netamt = jTextField7.getText();
        
        String st []={code,itemName,quty,Discount,netamt};
        mod.addRow(st);
        
        String mrp=jTextField2.getText();
        String disAllowed=jTextField2.getText();
        String invoiceNo=jTextField5.getText();
        */
        
        
        
        
    }//GEN-LAST:event_jTextField6KeyPressed

    private void jTable2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable2MouseEntered

    private void jButton3MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseReleased
        
        tableload();
    }//GEN-LAST:event_jButton3MouseReleased

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        Payment p=new Payment();
        p.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTextField6InputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jTextField6InputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6InputMethodTextChanged

    private void jTextField4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField4KeyPressed
        // TODO add your handling code here:
               int f=0;   
    String s1=jTextField4.getText();
    String s2=null;
    for(int i=0;i<s1.length();i++)
    {
      char a=s1.charAt(i);  
       
      if(Character.isLetter(a))
      {
           f=1;
        s1=s1.substring(0, i);   
      }
    }
    if(f==1)
    {
        JOptionPane.showMessageDialog(null,"character not allowed");
        jTextField4.setText(null);
    }  
        
    }//GEN-LAST:event_jTextField4KeyPressed

    private void jTextField5KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField5KeyPressed
        // TODO add your handling code here:
                int f=0;   
    String s1=jTextField5.getText();
    String s2=null;
    for(int i=0;i<s1.length();i++)
    {
      char a=s1.charAt(i);  
       
      if(Character.isLetter(a))
      {
           f=1;
        s1=s1.substring(0, i);   
      }
    }
    if(f==1)
    {
        JOptionPane.showMessageDialog(null,"character not allowed");
        jTextField5.setText(null);
    }
    }//GEN-LAST:event_jTextField5KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BillEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BillEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BillEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BillEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BillEdit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
