package bill;

import DBConnect.DBconnect;
import Interface.retun_damage_items;
import bsmanagementsystem.MainPage;
import static com.oracle.util.Checksums.update;
import interfa.Delivery;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author DELL
 */
public class Payment extends javax.swing.JFrame {

    private DefaultTableModel model;
    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    Statement st = null;

    int i_no = 0;

    /**
     * Creates new form Payment
     */
    public Payment() {
        initComponents();

        con = DBconnect.connect();
        showDate();
        showTime();
        
    }

   
      public void tableload()
     {
     try
     {
     String sql= "SELECT Item_Code,Item_Name,QTY,DiscountsP,Net_Amount FROM bill";
     pst = con.prepareStatement(sql);
     rs = pst.executeQuery();
          mod=new DefaultTableModel();  
     jTable1.setModel(DbUtils.resultSetToTableModel(rs));
     }
        
     catch(Exception e)
     {
        
     }
    
     }
     
    void showDate() {
        Date d = new Date();
        SimpleDateFormat s = new SimpleDateFormat("dd-MM-YYYY");
        jLabel4.setText(s.format(d));

    }

    void showTime() {
       new Timer(0, new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                Date d = new Date();
                SimpleDateFormat s = new SimpleDateFormat("hh:mm:ss");
                jLabel11.setText(s.format(d));
            }

        }
        ).start();
    }
    
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1366, 768));
        setMinimumSize(new java.awt.Dimension(1366, 768));
        setPreferredSize(new java.awt.Dimension(1366, 768));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setMaximumSize(new java.awt.Dimension(1366, 768));
        jPanel1.setMinimumSize(new java.awt.Dimension(1366, 768));
        jPanel1.setPreferredSize(new java.awt.Dimension(1366, 768));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
        });
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 39, 134, 30));

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField2KeyPressed(evt);
            }
        });
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(415, 39, 134, 30));

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(688, 39, 134, 30));

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        jTextField5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField5KeyPressed(evt);
            }
        });
        jPanel1.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 134, 30));

        jTextField6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField6KeyPressed(evt);
            }
        });
        jPanel1.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(415, 94, 134, 30));

        jTextField7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField7KeyPressed(evt);
            }
        });
        jPanel1.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 39, 134, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Invoice No");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 99, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("MRP");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 44, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Item Name");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 44, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Date");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 80, 92, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Quntity");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 99, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Discount");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 99, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Net Price");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(868, 44, -1, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("View invoice");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 610, 130, 36));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setText("Credit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1155, 238, 130, 36));

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setText("Reset");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 610, 130, 36));

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton7.setText("Delete");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 610, 130, 36));

        jButton8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton8.setText("Done");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1155, 169, 130, 36));

        jButton9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton9.setText("Cheque");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1155, 309, 130, 36));

        jTextField8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField8KeyPressed(evt);
            }
        });
        jPanel1.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(688, 94, 134, 30));

        jTextField9.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField9KeyPressed(evt);
            }
        });
        jPanel1.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 570, 134, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Balance");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 620, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Item code", "Item Name", "Quantity", "Discount", "Price"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 1109, 356));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Date");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 80, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Time");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 110, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Time");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 110, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Total");
        jLabel13.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jLabel13KeyPressed(evt);
            }
        });
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 530, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("Discount Allowed");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(868, 99, -1, -1));
        jPanel1.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 94, 134, 30));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("Item Code");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 44, -1, -1));

        jTextField10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField10ActionPerformed(evt);
            }
        });
        jTextField10.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField10KeyPressed(evt);
            }
        });
        jPanel1.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 620, 130, 30));

        jTextField11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField11.setText("0.00");
        jTextField11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField11ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 517, 134, 30));

        jTextField12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField12ActionPerformed(evt);
            }
        });
        jTextField12.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField12KeyPressed(evt);
            }
        });
        jPanel1.add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 134, 30));

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton5.setText("BillId");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, -1, -1));
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 140, -1, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 20, 110, 40));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bill/backgrnd1.png"))); // NOI18N
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1350, 700));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1350, 740));

        jMenu1.setText("File");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Menu");
        jMenu2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        jMenuItem1.setText("Bill Edit");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuItem2.setText("Others");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuItem3.setText("Sale Report");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuItem4.setText("Return");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuItem5.setText("Delivery");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(1366, 768));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        SaleReport r = new SaleReport();
        r.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
        
  
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        int x =JOptionPane.showConfirmDialog(null,"Do You want Delete This?");
        
        
        if(x==0){
        //String billId=jTextField1.getText();    
        //String invoiceid=jTextField1.getText();
        String billId=jTextField12.getText();
        String itemCode=jTextField1.getText();
        String itemName=jTextField3.getText();
        String quty=jTextField6.getText(); 
        String discount=jTextField8.getText();
        String netPrice=jTextField7.getText();
        String mrp=jTextField2.getText();
       // String date=jTextField8.getText();
       String discountAllowed=jTextField4.getText();
      
        
        
         
           String sql ="DELETE from bill where BillId = "+itemCode+" ";
          
            try
            {
                
            pst=con.prepareStatement(sql);
            pst.execute(); 
            JOptionPane.showMessageDialog(null, "Deleted");
               //tableload();
               }
            catch(Exception e)
            {
            JOptionPane.showMessageDialog(null, e);
            e.printStackTrace();
            }
        }
        
        
         
        
        
        
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        ViewInvoice p=new ViewInvoice ();
        p.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:

        //int r = jTable1.getSelectedRow();
        String code = jTextField1.getText();
        int invoiceId = Integer.parseInt(jTextField5.getText());
        Float saleAmount = Float.parseFloat(jTextField2.getText());
        Float quty = Float.parseFloat(jTextField6.getText());
        Float discount = Float.parseFloat(jTextField8.getText());
        Float netamt = Float.parseFloat(jTextField7.getText());
        String itemName = jTextField3.getText();
        String date = jLabel4.getText();
        Float DisctAllowed=Float.parseFloat(jTextField4.getText());

        try {

            String qry = ("INSERT INTO bill (InvoiceId,item_Code,Item_Name,QTY,bill_Date,MRP,DiscountsP,Discounts_Allowed,Net_Amount)VALUES(" + invoiceId + ",'" + code + "','" + itemName + "'," + quty + ",'"+date+"'," + saleAmount + "," + discount + "," + DisctAllowed + "," + netamt + ")");
             pst = con.prepareStatement(qry);
                    //Statement pst=conn.createStatement();
            // tableload();
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Added");

           
            
             
                    //Payment_2 p=new Payment_2();
           
        } catch (Exception e) {

            JOptionPane.showMessageDialog(null, e);
            System.out.println(e);
            e.printStackTrace();
        }
       
        /* {
            Object[] colomns = {"Item_Code", "Item_Name", "QTY", "DiscountsP", "Net_Amount"};
            model = new DefaultTableModel();
            model.setColumnIdentifiers(colomns);
            jTable1.setModel(model);

            Object[] row = new Object[5];

            row[0] = jTextField1.getText();
            row[1] = jTextField3.getText();
            row[2] = jTextField6.getText();
            row[3] = jTextField8.getText();
            row[4] = jTextField7.getText();
            model.addRow(row);

        } catch (Exception e) {

            //JOptionPane.showMessageDialog(null, e);
            System.out.println(e);
            e.printStackTrace();
            
                
        try{
            Object[] row = new Object[5];

            row[0] = jTextField1.getText();
            row[1] = jTextField3.getText();
            row[2] = jTextField6.getText();
            row[3] = jTextField8.getText();
            row[4] = jTextField7.getText();
            model.addRow(row);
        }   
        catch(Exception e1)
        {
            e1.printStackTrace();
        }
         tableload();
        
       // DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
        //model.addRow(new Object[]{jTextField1.getText(),jTextField3.getText(),jTextField6.getText(),jTextField8.getText(),jTextField7.getText()});
    
        double tot=0;
        for(int i=0;i<jTable1.getRowCount();i++)
        {
            float amount=Float.parseFloat((String)jTable1.getValueAt(i,4));
            tot+=amount;
        }
        jLabel12.setText(String.valueOf(tot));
        
        try{
            String update="";
        }
        catch(Exception e2)
        {
            e.printStackTrace();
        }
        }
       */ 
        
        
         //DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
        //model.addRow(new Object[]{jTextField1.getText(),jTextField3.getText(),jTextField6.getText(),jTextField8.getText(),jTextField7.getText()});
    
        double tot=0;
        for(int i=0;i<jTable1.getRowCount();i++)
        {
            Double amount=Double.parseDouble((String)jTable1.getValueAt(i,4));
            tot+=amount;
        }
        jTextField11.setText(String.valueOf(tot));
        
        try{
            String update="";
        }
        catch(Exception e2)
        {
            e2.printStackTrace();
        }
        
        jTextField1.setText(null);
        jTextField2.setText(null);
        jTextField3.setText(null);
        jTextField4.setText(null);
        
        jTextField6.setText(null);
        jTextField7.setText(null);
        jTextField8.setText(null);
        
        try {
            //String update=
            //ResultSet rs = pst.executeQuery();
        } catch (Exception ex) {
           // ex.printStackTrace();
            try {
                    Float update = Float.parseFloat(jTextField6.getText());
                if(rs.next()){
                    //String quantity=rs.getString("QTY");//get value
                    //jTextField10.setText(quantity);
                    Float bill=Float.parseFloat(rs.getString("QTY"));
                }
                 Float bill=Float.parseFloat(rs.getString("QTY"));
                    Float updatedOne=bill-update;
                    String sql2="UPDATE bill SET  Quantity='"+updatedOne+"' from  where ProductID="+jTextField1.getText()+"";
            } catch (Exception ex1) {
                ex1.printStackTrace();
            }
           //String sql2="UPDATE bill SET  item_Code='"+itemcode+"',Item_Name='"+name+  
           // Float updatedOne=quantity-update;
        }
        
        
        
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        jTextField1.setText(null);
        jTextField2.setText(null);
        jTextField3.setText(null);
        
        jTextField6.setText(null);
        jTextField7.setText(null);
        jTextField8.setText(null);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String code = jTextField1.getText();
        int invoiceId = Integer.parseInt(jTextField5.getText());
        Float saleAmount = Float.parseFloat(jTextField2.getText().trim());
        Float quty = Float.parseFloat(jTextField6.getText().trim());
        Float discount = Float.parseFloat(jTextField8.getText().trim());
        Float netamt = Float.parseFloat(jTextField7.getText());
        String itemName = jTextField3.getText();
        String date = jLabel4.getText();
        Float DisctAllowed=Float.parseFloat(jTextField4.getText());

        try {

            String qry = ("INSERT INTO creditsales (Item_ID,Item_Name,QTY,MRP,DiscountsP,Discounts_Allowed,Date,Net_Amount,Invoice_ID)VALUES('" + code+ "','" + itemName + "'," + quty + "," +saleAmount+ "," + discount + "," +DisctAllowed+ "," + date+ "," + netamt + ","+invoiceId+")");
            PreparedStatement pst = con.prepareStatement(qry);
                //Statement pst=conn.createStatement();
            //tableload();
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Added");
        } catch (Exception e) {

            JOptionPane.showMessageDialog(null, e);
            System.out.println(e);

        }
        
        
         double tot=0;
        for(int i=0;i<jTable1.getRowCount();i++)
        {
            Double amount=Double.parseDouble((String)jTable1.getValueAt(i,4));
            tot+=amount;
        }
        jTextField11.setText(String.valueOf(tot));
        
        try{
            String update="";
        }
        catch(Exception e2)
        {
            e2.printStackTrace();
        }
        
        jTextField1.setText(null);
        jTextField2.setText(null);
        jTextField3.setText(null);
        jTextField4.setText(null);
        
        jTextField6.setText(null);
        jTextField7.setText(null);
        jTextField8.setText(null);
        
        
        
        

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:

         String code = jTextField1.getText();
        int invoiceId = Integer.parseInt(jTextField5.getText());
        Float saleAmount = Float.parseFloat(jTextField2.getText().trim());
        Float quty = Float.parseFloat(jTextField6.getText().trim());
        Float discount = Float.parseFloat(jTextField8.getText().trim());
        Float netamt = Float.parseFloat(jTextField7.getText());
        String itemName = jTextField3.getText();
        String date = jLabel4.getText();
        Float DisctAllowed=Float.parseFloat(jTextField4.getText());


        try {

            String qry = ("INSERT INTO chequepayment (Invoice_ID,Item_Code,Item_Name,netPrice,Date,QTY,MRP,DiscountsP,Discounts_Allowed)VALUES(" + invoiceId + ",'" + code + "','" + itemName+ "'," + netamt + ",'" + date + "'," + quty + "," +saleAmount + "," + discount+ ","+DisctAllowed+")");
            PreparedStatement pst = con.prepareStatement(qry);
                //Statement pst=conn.createStatement();
            //tableload();
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Added");
        } catch (Exception e) {

            JOptionPane.showMessageDialog(null, e);
            System.out.println(e);

        }
         double tot=0;
        for(int i=0;i<jTable1.getRowCount();i++)
        {
            Double amount=Double.parseDouble((String)jTable1.getValueAt(i,4));
            tot+=amount;
        }
        jTextField11.setText(String.valueOf(tot));
        
        try{
            String update="";
        }
        catch(Exception e2)
        {
            e2.printStackTrace();
        }
        
        jTextField1.setText(null);
        jTextField2.setText(null);
        jTextField3.setText(null);
        jTextField4.setText(null);
        
        jTextField6.setText(null);
        jTextField7.setText(null);
        jTextField8.setText(null);
        
        
        
        

    }//GEN-LAST:event_jButton9ActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        BillEdit b = new BillEdit();
        b.setVisible(true);

    }//GEN-LAST:event_jMenu2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        BillEdit b = new BillEdit();
        b.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        Others t = new Others();
        t.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int r = jTable1.getSelectedRow();
        TableModel model=jTable1.getModel();
        //assign data to variables
        String ItemCode = jTable1.getValueAt(r, 0).toString();
        String ItemName = jTable1.getValueAt(r, 1).toString();
        String Quantity = jTable1.getValueAt(r, 2).toString();
        String discount = jTable1.getValueAt(r, 3).toString();
        String price = jTable1.getValueAt(r, 4).toString();
        //assigning data to textfields and combo box
        jTextField1.setText(ItemCode);
        jTextField3.setText(ItemName);
        jTextField6.setText(Quantity);
        jTextField8.setText(discount);
        jTextField7.setText(price);
    }//GEN-LAST:event_jTable1MouseClicked

    private void jTextField2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyPressed
        // TODO add your handling code here:
            int f=0;   
    String s1=jTextField2.getText();
    String s2=null;
    for(int i=0;i<s1.length();i++)
    {
      char a=s1.charAt(i);  
       
      if(Character.isLetter(a))
      {
           f=1;
        s1=s1.substring(0, i);   
      }
    }
    if(f==1)
    {
        JOptionPane.showMessageDialog(null,"character not allowed");
        jTextField2.setText(null);
    }
    }//GEN-LAST:event_jTextField2KeyPressed

    private void jTextField7KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField7KeyPressed
        // TODO add your handling code here:
        Float saleAmount1;
        Float quty1;
        Float discount1;
        Float discunt;
       //Float Sum=0f;

        //saleAmount1=Float.parseFloat(jTextField2.getText());
        //quty1=Float.parseFloat(jTextField6.getText());
        //discount1=Float.parseFloat(jTextField8.getText());
        
        Pay1 p = new Pay1();
        p.setSaleAmount1(Float.parseFloat(jTextField2.getText()));
        p.setDiscount1(Float.parseFloat(jTextField8.getText()));
        p.setQuty1(Float.parseFloat(jTextField6.getText()));
/*
        Double total = p.cal();
        jTextField7.setText(String.valueOf(total));
        
        double discount2=p.cal2();
        jTextField4.setText(String.valueOf(discount2));
       */ 
        //jTextField7.setText(total);
        //jTextField4.set
        
         double total=p.cal();
        DecimalFormat decimalFormat = new DecimalFormat("#.##");
        float total1;
        total1 = Float.valueOf(decimalFormat.format(total));
        jTextField7.setText(String.valueOf(total1));
        double discount=p.cal2();
        DecimalFormat decimalFormat1 = new DecimalFormat("#.##");
        float discount2;
        discount2 = Float.valueOf(decimalFormat.format(discount));
        jTextField4.setText(String.valueOf(discount2));
        
        
        
        String code = jTextField1.getText();
        String itemName = jTextField3.getText();
        String quty = jTextField6.getText();
        String Discount = jTextField8.getText();
        String netamt = jTextField7.getText();
        
        String st []={code,itemName,quty,Discount,netamt};
        mod.addRow(st);
        
        String mrp=jTextField2.getText();
        String disAllowed=jTextField2.getText();
        String invoiceNo=jTextField5.getText();
        
      /*  jTextField1.setText(null);
        jTextField2.setText(null);
        jTextField3.setText(null);
        jTextField4.setText(null);
        
        jTextField6.setText(null);
        jTextField7.setText(null);
        jTextField8.setText(null);
        */
       
    }//GEN-LAST:event_jTextField7KeyPressed

    private void jLabel13KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel13KeyPressed
        // TODO add your handling code here:
       try {
            rs=st.executeQuery("select max(InvoiceId) from bill");
            
            rs.next();
              if(rs!=null)
              {
                  
                  i_no=rs.getInt(1);
              i_no++;
              } 
           else
                    i_no=1;
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        
    }//GEN-LAST:event_jLabel13KeyPressed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed
        DefaultTableModel mod;
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        mod=new DefaultTableModel();
        jTable1.setModel(mod);
        mod.addColumn("Item Code");
        mod.addColumn("Item Name");
        mod.addColumn("Quantity");
        mod.addColumn("Discount");
        mod.addColumn("Net Amount");
        mod.addColumn("BillId");
    }//GEN-LAST:event_formWindowOpened

    private void jTextField8KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField8KeyPressed
        // TODO add your handling code here:
        
        int f=0;   
    String s1=jTextField8.getText();
    String s2=null;
    for(int i=0;i<s1.length();i++)
    {
      char a=s1.charAt(i);  
       
      if(Character.isLetter(a))
      {
           f=1;
        s1=s1.substring(0, i);   
      }
    }
    if(f==1)
    {
        JOptionPane.showMessageDialog(null,"character not allowed");
        jTextField4.setText(null);
    }
    }//GEN-LAST:event_jTextField8KeyPressed

    private void jTextField6KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField6KeyPressed
        // TODO add your handling code here:
            int f=0;   
    String s1=jTextField6.getText();
    String s2=null;
    for(int i=0;i<s1.length();i++)
    {
      char a=s1.charAt(i);  
       
      if(Character.isLetter(a))
      {
           f=1;
        s1=s1.substring(0, i);   
      }
    }
    if(f==1)
    {
        JOptionPane.showMessageDialog(null,"character not allowed");
        jTextField6.setText(null);
    }
    }//GEN-LAST:event_jTextField6KeyPressed

    private void jTextField5KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField5KeyPressed
        // TODO add your handling code here:
            int f=0;   
    String s1=jTextField5.getText();
    String s2=null;
    for(int i=0;i<s1.length();i++)
    {
      char a=s1.charAt(i);  
       
      if(Character.isLetter(a))
      {
           f=1;
        s1=s1.substring(0, i);   
      }
    }
    if(f==1)
    {
        JOptionPane.showMessageDialog(null,"character not allowed");
        jTextField5.setText(null);
    }
    }//GEN-LAST:event_jTextField5KeyPressed

    private void jTextField9KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField9KeyPressed
      
       //Float total;
       //Float mony;
       
       Pay1 p2=new Pay1();
       p2.setTotal(Float.parseFloat(jTextField11.getText()));
        p2.setMony(Float.parseFloat(jTextField9.getText()));
      
        double getBalance=p2.getBalance();
       //String pass=getText(balance); 
       DecimalFormat decimalFormat = new DecimalFormat("#.##");
        float total4;
        total4 = Float.valueOf(decimalFormat.format(getBalance));
       jTextField10.setText(String.valueOf(total4));
    }//GEN-LAST:event_jTextField9KeyPressed

    private void jTextField10KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField10KeyPressed
        // TODO add your handling code here:
       // String total=
         String b_code="select max(InvoiceId) from bill";
        try {
            pst = con.prepareStatement(b_code);
            rs = pst.executeQuery();
            rs.next();
            int a=0;
            a = rs.getInt(1);
            if(a==0)
            {
                a++;
                jTextField5.setText(""+a);
            }

            else{
                a++;
                jTextField5.setText(""+a);
            }
            //jTextField5.setText(""+a);
            //System.out.println(String.format("max(Book_code) is %d", a));
        }
        catch(Exception e) {
            e.printStackTrace();
        }
        
        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        dtm.setRowCount(0);
    }//GEN-LAST:event_jTextField10KeyPressed

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
        // TODO add your handling code here:
        String itemCode=jTextField1.getText();
        
        try{
            String sql="select CostPerUnit ,ProductName from products where ProductID='"+itemCode+"'";
         pst=con.prepareStatement(sql);
           
            ResultSet rs = pst.executeQuery();
            if(rs.next())
            {
                String prod=rs.getString("CostPerUnit");//get value
                jTextField2.setText(prod);
                String prod1=rs.getString("ProductName");//get value
                jTextField3.setText(prod1);
                
            }
        }
        
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jTextField1KeyPressed

    private void jTextField11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField11ActionPerformed

    private void jTextField12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField12ActionPerformed

    private void jTextField12KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField12KeyPressed
        // TODO add your handling code here:
        
        /*String BillId=jTextField12.getText();
        
         try{
            String sql="select BillId,InvoiceId,item_Code,Item_Name,QTY,bill_Date,MRP,DiscountsP,Discounts_Allowed,Net_Amount from bill where BillId='"+BillId+"'";
         pst=con.prepareStatement(sql);
           
            ResultSet rs = pst.executeQuery();
            if(rs.next())
            {
                String InvoiceId=rs.getString("InvoiceId");//get value
                jTextField5.setText(InvoiceId);
                String item_Code=rs.getString("item_Code");//get value
                jTextField1.setText(item_Code);
                String Item_Name=rs.getString("Item_Name");//get value
                jTextField3.setText(Item_Name);
                String QTY=rs.getString("QTY");//get value
                jTextField6.setText(QTY);
                String bill_Date=rs.getString("bill_Date");//get value
                jLabel9.setText(bill_Date);
                String MRP=rs.getString("MRP");//get value
                jTextField2.setText(MRP);
                String DiscountsP=rs.getString("DiscountsP");//get value
                jTextField8.setText(DiscountsP);
                String Discounts_Allowed=rs.getString("Discounts_Allowed");//get value
                jTextField4.setText(DiscountsP);
                String Net_Amount=rs.getString("Net_Amount");//get value
                jTextField7.setText(Net_Amount);
                
              
                
                
            }
        }
        
        catch(Exception e)
        {
            e.printStackTrace();
        }
         
         
         String sql ="DELETE from bill where BillId = "+BillId+" ";
          
            try
            {
                
            pst=con.prepareStatement(sql);
            pst.execute(); 
            JOptionPane.showMessageDialog(null, "Deleted");
               //tableload();
               }
            catch(Exception e)
            {
            JOptionPane.showMessageDialog(null, e);
            e.printStackTrace();
            }
         
         */
        
    }//GEN-LAST:event_jTextField12KeyPressed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        String BillId=jTextField12.getText();
         String sql ="DELETE from bill where BillId = "+BillId+" ";
          
            try
            {
                
            pst=con.prepareStatement(sql);
            pst.execute(); 
            JOptionPane.showMessageDialog(null, "Deleted");
               //tableload();
               }
            catch(Exception e)
            {
            JOptionPane.showMessageDialog(null, e);
            e.printStackTrace();
            }
         
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTextField10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField10ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        Delivery del = new Delivery();
        del.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        retun_damage_items ret= new retun_damage_items();
        ret.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new MainPage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Payment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
