/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bsmanagementsystem.internalJFrames;

import javax.swing.JOptionPane;

/**
 *
 * @author Rashan
 */
public class Finance extends javax.swing.JInternalFrame {

    /**
     * Creates new form Finance
     */
    public Finance() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(853, 635));
        setMinimumSize(new java.awt.Dimension(853, 635));
        setPreferredSize(new java.awt.Dimension(853, 635));

        jPanel1.setMaximumSize(new java.awt.Dimension(853, 635));
        jPanel1.setMinimumSize(new java.awt.Dimension(853, 635));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Income/Expense Statement");
        jButton1.setMaximumSize(new java.awt.Dimension(250, 46));
        jButton1.setMinimumSize(new java.awt.Dimension(250, 46));
        jButton1.setPreferredSize(new java.awt.Dimension(250, 46));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(134, 220, -1, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("Statement of Financial Position");
        jButton2.setMaximumSize(new java.awt.Dimension(240, 46));
        jButton2.setMinimumSize(new java.awt.Dimension(240, 46));
        jButton2.setPreferredSize(new java.awt.Dimension(240, 46));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(134, 334, 250, -1));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setText("Statement of Cash Flows");
        jButton3.setMaximumSize(new java.awt.Dimension(250, 46));
        jButton3.setMinimumSize(new java.awt.Dimension(250, 46));
        jButton3.setPreferredSize(new java.awt.Dimension(250, 46));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(134, 448, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Financial Statements");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setPreferredSize(new java.awt.Dimension(200, 50));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, 270, -1));

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setText("Print");
        jButton4.setMaximumSize(new java.awt.Dimension(130, 36));
        jButton4.setMinimumSize(new java.awt.Dimension(130, 36));
        jButton4.setPreferredSize(new java.awt.Dimension(130, 36));
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(528, 220, -1, 46));

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton5.setText("Print");
        jButton5.setMaximumSize(new java.awt.Dimension(130, 36));
        jButton5.setMinimumSize(new java.awt.Dimension(130, 36));
        jButton5.setPreferredSize(new java.awt.Dimension(130, 36));
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(528, 334, -1, 46));

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton6.setText("Print");
        jButton6.setMaximumSize(new java.awt.Dimension(130, 36));
        jButton6.setMinimumSize(new java.awt.Dimension(130, 36));
        jButton6.setPreferredSize(new java.awt.Dimension(130, 36));
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(528, 448, -1, 46));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Quater");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(388, 122, 109, 38));

        jComboBox1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Please Select", "1", "2", "3", "4" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(586, 123, 148, 38));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Year");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(388, 63, 109, 38));

        jComboBox2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Please Select", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2025", "2026", "2027", "2028", "2029", "2030" }));
        jPanel1.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(586, 62, 148, 42));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/backgrnd1.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 837, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 599, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        int n;

        n = chkQuater();

        if (n == 0){

        }
        else if (n == 1){
            //show the relevant report
        }
        else if (n == 2){

        }
        else if (n== 3){

        }
        else{
            
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        int n;

        n = chkQuater();

        if (n == 0){

        }
        else if (n == 1){
            //show the relevant report
        }
        else if (n == 2){

        }
        else if (n== 3){

        }
        else{
            
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        int n;

        n = chkQuater();

        if (n == 0){

        }
        else if (n == 1){
            //show the relevant report
        }
        else if (n == 2){

        }
        else if (n== 3){

        }
        else{
            
        }


    }//GEN-LAST:event_jButton3ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

     
        private int chkQuater(){
        
        String[] arr = {"1","2","3","4"};
        String a = jComboBox1.getSelectedItem().toString();
        int i=0;
        int n = -1;
        if (a == "Please Select"){
          
            JOptionPane.showMessageDialog(null,"Please Select A Quarter");
            return n;
        }
        else{     
        n = loop(i,arr,a);

        return n;
        }
            
    }
    
      private int loop(int i,String arr[],String a){
        
        int c = 0;
        
        if(!"".equals(a)){
        while (i < 5){
            
            if (arr[i] == null ? a == null : arr[i].equals(a)){
                c = i;
            }
            else{
                return i++;
            }
        }
        }
        
        return c;
        
      }  
      
      private String getYearSelected(){
          
          return jComboBox2.getSelectedItem().toString();
      }
      
      private String getQuaterSelected(){
          
          return jComboBox1.getSelectedItem().toString();
      }
      
      
      /* private int chkMonth(){
        
        String[] arr = {"January","February","March","April","May","June","July","August","September","Octomber","November","December"};
        String a = jComboBox1.getSelectedItem().toString();
        int i=0;
        int n;
        
        n = loop(i,arr,a);

        return n;
            
    }

    private int loop(int i,String arr[],String a){
        
        int c = -1;
        
        if(!"".equals(a)){
        while (i < 12){
            
            if (arr[i] == null ? a == null : arr[i].equals(a)){
                c = i;
            }
            else{
                return i++;
            }
        }
        }
        
        return c;
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
