/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import database.DBconnect;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author user
 */
public class Loan extends javax.swing.JFrame {

    Connection con =null;
    PreparedStatement pst =null;
    ResultSet rs=null;
    /**
     * Creates new form Loan
     */
    public Loan() {
        initComponents();
         //connect to DB
        con =DBconnect.connect();
        
        //load table
        tableload();
        tableloadtt();
    }
    
    
        public void tableload()
    {
        try 
        {
       
        String sql="select l.Emp_ID,e.Emp_Name,l.Salary from loans l,employee e where e.Emp_ID=l.Emp_ID";
        pst=con.prepareStatement(sql);
        rs= pst.executeQuery();
        
        loan.setModel(DbUtils.resultSetToTableModel(rs));
        
        }
        catch(Exception e)
        {
        }
    }
        
          public void tableloadtt()
    {
        try 
        {
        
        String sql="select l.Emp_ID,e.Emp_Name,l.Salary,l.Loan_Type,l.Percentage_Allowed,l.Loan_Amount,l.Obtained_on,l.Duration from loans l,employee e where e.Emp_ID=l.Emp_ID";
        pst=con.prepareStatement(sql);
        rs= pst.executeQuery();
        
        tt.setModel(DbUtils.resultSetToTableModel(rs));
        
        }
        catch(Exception e)
        {
        }
    }
          
     private void clearfields()
     {
        
        ii.setText("");
        ss.setText("");
        loanamount.setText("");
        per.setText("");
        datebox.setDate(null);
        combo1.setSelectedIndex(0);;
        combo2.setSelectedIndex(0);;
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDayChooser1 = new com.toedter.calendar.JDayChooser();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        per = new javax.swing.JTextField();
        ii = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        loan = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        ss = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tt = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        loanamount = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        datebox = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        combo1 = new javax.swing.JComboBox();
        combo2 = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1366, 768));
        setMinimumSize(new java.awt.Dimension(1366, 768));
        setPreferredSize(new java.awt.Dimension(1366, 768));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Calculate Loan");
        jButton1.setMaximumSize(new java.awt.Dimension(130, 36));
        jButton1.setMinimumSize(new java.awt.Dimension(130, 36));
        jButton1.setPreferredSize(new java.awt.Dimension(130, 36));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 299, 140, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("Assign");
        jButton2.setMaximumSize(new java.awt.Dimension(130, 36));
        jButton2.setMinimumSize(new java.awt.Dimension(130, 36));
        jButton2.setPreferredSize(new java.awt.Dimension(130, 36));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 422, 140, -1));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(279, 58, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("ID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 135, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Percentage");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 192, -1, -1));
        getContentPane().add(per, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 190, 125, -1));
        getContentPane().add(ii, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 133, 125, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("%");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(318, 192, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Amount");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 354, -1, -1));

        loan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Name", "Salary Level"
            }
        ));
        loan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(loan);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(414, 121, 620, 171));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Salary");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 164, -1, -1));
        getContentPane().add(ss, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 162, 125, -1));

        tt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tt.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ttMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tt);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(414, 435, 620, 215));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Employee Loans");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 53, 212, 36));

        loanamount.setText("calculated amount");
        getContentPane().add(loanamount, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 353, 113, 21));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Date");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 381, -1, 25));

        datebox.setDateFormatString("yyyy-MM-dd");
        getContentPane().add(datebox, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 381, 102, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Loan Type");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 221, -1, -1));

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setText("Back");
        jButton4.setMaximumSize(new java.awt.Dimension(130, 36));
        jButton4.setMinimumSize(new java.awt.Dimension(130, 36));
        jButton4.setPreferredSize(new java.awt.Dimension(130, 36));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(989, 57, 140, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Duration");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, -1, -1));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setText("Edit");
        jButton3.setMaximumSize(new java.awt.Dimension(130, 36));
        jButton3.setMinimumSize(new java.awt.Dimension(130, 36));
        jButton3.setPreferredSize(new java.awt.Dimension(130, 36));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 422, 140, -1));

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton5.setText("Clear Fields");
        jButton5.setMaximumSize(new java.awt.Dimension(130, 36));
        jButton5.setMinimumSize(new java.awt.Dimension(130, 36));
        jButton5.setPreferredSize(new java.awt.Dimension(130, 36));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 476, 140, -1));

        combo1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Loan Type", "Short-time Loan", "Long-term", "Salary advance" }));
        getContentPane().add(combo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 219, -1, -1));

        combo2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Duration", "1 week", "2 weeks", "3 weeks", " " }));
        getContentPane().add(combo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 248, 125, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bill/backgrnd1.png"))); // NOI18N
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 770));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void loanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loanMouseClicked
        // mouse click
        try
        {
        int r=loan.getSelectedRow();
        String Id=loan.getValueAt(r, 0).toString();
        String sl=loan.getValueAt(r, 2).toString();
        
        ii.setText(Id);
        ss.setText(sl);
        }
        catch(Exception e)
                {}
        
    }//GEN-LAST:event_loanMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        // assign button
        
        String Id=ii.getText();
        String i=loanamount.getText();
        String p=per.getText();
        String date;
        date = ((JTextField)datebox.getDateEditor().getUiComponent()).getText();
        String t1=combo1.getSelectedItem().toString();
        String t2=combo2.getSelectedItem().toString();
        
        try
        {
        String q="Update loans set Loan_Type='"+t1+"',Loan_amount='"+i+"',Duration='"+t2+"',Obtained_on='"+date+"',Percentage_Allowed='"+p+"' where Emp_ID='"+Id+"'  ";
        pst=con.prepareStatement(q);
        pst.execute();
        
        //load table
        tableloadtt();
        clearfields();
        }
        catch(Exception ex)
        {
        }
        
        

        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //claculate button
        
      
        float n=new Float(per.getText());
        float l=new Float(ss.getText());
        
        float G=(l*n)/100;
        
        loanamount.setText(String.valueOf(G));
 
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ttMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ttMouseClicked
       try
       {     
        int r=tt.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel)tt.getModel();
        
        String Id=tt.getValueAt(r, 0).toString();
        String s=tt.getValueAt(r, 2).toString();
        String prc=tt.getValueAt(r, 4).toString();
        String lt=tt.getValueAt(r, 3).toString();
        String dur=tt.getValueAt(r, 7).toString();
        String amt=tt.getValueAt(r, 5).toString();
        Date date = new SimpleDateFormat("yyyy-MM-dd").parse((String)model.getValueAt(r, 6).toString());
        
        loanamount.setText(amt);
        combo2.setSelectedItem(dur);
        combo1.setSelectedItem(lt);
        per.setText(prc);
        datebox.setDate(date);
        ii.setText(Id);
        ss.setText(s);
       }
       catch(Exception e)
       {}
       
    }//GEN-LAST:event_ttMouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        HRM l=new HRM();
        l.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
          // Update records
        
        int x=JOptionPane.showConfirmDialog(null,"Do you want to Update?");
       if(x==0)
       {
           
        String Id=ii.getText();
        String i=loanamount.getText();
        String p=per.getText();
        String date;
        date = ((JTextField)datebox.getDateEditor().getUiComponent()).getText();
        String t1=combo1.getSelectedItem().toString();
        String t2=combo2.getSelectedItem().toString();
         
        try{
             
        String q="Update loans set Loan_Type='"+t1+"',Loan_amount='"+i+"',Duration='"+t2+"',Obtained_on='"+date+"',Percentage_Allowed='"+p+"' where Emp_ID='"+Id+"'  ";
        pst=con.prepareStatement(q);
       
        int result=pst.executeUpdate();
        tableloadtt();
        if(result == 1){
            JOptionPane.showMessageDialog(this,"Succusfully updated");
        clearfields();
           
        }
        }
        catch(Exception e)
        {}
        
    }  
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // clear fields
        clearfields();
        
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Loan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Loan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Loan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Loan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Loan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox combo1;
    private javax.swing.JComboBox combo2;
    private com.toedter.calendar.JDateChooser datebox;
    private javax.swing.JTextField ii;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private com.toedter.calendar.JDayChooser jDayChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable loan;
    private javax.swing.JLabel loanamount;
    private javax.swing.JTextField per;
    private javax.swing.JTextField ss;
    private javax.swing.JTable tt;
    // End of variables declaration//GEN-END:variables
}
