/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfa;

import Codes.Constants;
import Codes.ValidationChecker;
import bill.BillEdit;
import bill.Payment;
import controller.DeliveryController;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Sandun
 */
public class Delivery extends javax.swing.JFrame {

    private ButtonGroup paymentButtonGroup;
    private ButtonGroup statusButtonGroup;

    /**
     * Creates new form Delivery
     */
    public Delivery() {
        initComponents();
        statusButtonGroup = new ButtonGroup();
        statusButtonGroup.add(ddeli);
        statusButtonGroup.add(dpen);
        paymentButtonGroup = new ButtonGroup();
        paymentButtonGroup.add(ddaid);
        paymentButtonGroup.add(doncash);
        try {
            dTable.setModel(DbUtils.resultSetToTableModel(DeliveryController.getAllDeliveryResultSet()));
        } catch (SQLException ex) {
            Logger.getLogger(Delivery.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    Delivery(String jxBrowser_Google_Maps) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Donedeleiver = new javax.swing.JButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        dTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        delivid = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        daddress = new javax.swing.JTextArea();
        Mapdeliver = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        ddeli = new javax.swing.JRadioButton();
        dpen = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        ddaid = new javax.swing.JRadioButton();
        doncash = new javax.swing.JRadioButton();
        delevradd = new javax.swing.JButton();
        delevrupdate = new javax.swing.JButton();
        delevrdelete = new javax.swing.JButton();
        delevrcf = new javax.swing.JButton();
        ditemcode = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        ditemname = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        dqty = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        dinvoiceid = new javax.swing.JTextField();
        dcustid = new javax.swing.JTextField();
        dsearch = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();

        Donedeleiver.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Donedeleiver.setText("Done");
        Donedeleiver.setMaximumSize(new java.awt.Dimension(130, 36));
        Donedeleiver.setMinimumSize(new java.awt.Dimension(130, 36));
        Donedeleiver.setPreferredSize(new java.awt.Dimension(130, 36));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1366, 768));
        setMinimumSize(new java.awt.Dimension(1366, 768));
        setPreferredSize(new java.awt.Dimension(1366, 768));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        dTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(dTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 130, 930, 509));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Delivery");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 10, -1, 39));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Delivery ID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 60, -1, -1));
        getContentPane().add(delivid, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 58, 137, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Address");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 412, -1, -1));

        daddress.setColumns(20);
        daddress.setRows(5);
        jScrollPane2.setViewportView(daddress);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 378, 199, -1));

        Mapdeliver.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Mapdeliver.setText("Map");
        Mapdeliver.setMaximumSize(new java.awt.Dimension(130, 36));
        Mapdeliver.setMinimumSize(new java.awt.Dimension(130, 36));
        Mapdeliver.setPreferredSize(new java.awt.Dimension(130, 36));
        Mapdeliver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MapdeliverActionPerformed(evt);
            }
        });
        getContentPane().add(Mapdeliver, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 502, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Status");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 560, -1, -1));

        ddeli.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ddeli.setSelected(true);
        ddeli.setText("Deliverd");
        ddeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ddeliActionPerformed(evt);
            }
        });
        getContentPane().add(ddeli, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 556, -1, -1));

        dpen.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        dpen.setText("Pending");
        getContentPane().add(dpen, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 556, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Payment");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 599, -1, -1));

        ddaid.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ddaid.setSelected(true);
        ddaid.setText("Paid");
        getContentPane().add(ddaid, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 599, -1, -1));

        doncash.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        doncash.setText("On cash delivery");
        doncash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doncashActionPerformed(evt);
            }
        });
        getContentPane().add(doncash, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 599, -1, -1));

        delevradd.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        delevradd.setText("Add");
        delevradd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delevraddActionPerformed(evt);
            }
        });
        getContentPane().add(delevradd, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 680, -1, -1));

        delevrupdate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        delevrupdate.setText("Update");
        delevrupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delevrupdateActionPerformed(evt);
            }
        });
        getContentPane().add(delevrupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 680, -1, -1));

        delevrdelete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        delevrdelete.setText("Delete");
        delevrdelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delevrdeleteActionPerformed(evt);
            }
        });
        getContentPane().add(delevrdelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 680, -1, -1));

        delevrcf.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        delevrcf.setText("Clear Fields");
        delevrcf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delevrcfActionPerformed(evt);
            }
        });
        getContentPane().add(delevrcf, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 680, -1, -1));
        getContentPane().add(ditemcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 109, 138, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Item Name");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 154, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Item Code");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 114, -1, -1));
        getContentPane().add(ditemname, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 152, 138, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Invoice ID");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 262, -1, -1));

        dqty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dqtyActionPerformed(evt);
            }
        });
        dqty.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                dqtyKeyReleased(evt);
            }
        });
        getContentPane().add(dqty, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 208, 138, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Quantity");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 210, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Customer ID");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 311, -1, -1));

        dinvoiceid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                dinvoiceidKeyReleased(evt);
            }
        });
        getContentPane().add(dinvoiceid, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 260, 138, -1));
        getContentPane().add(dcustid, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 309, 138, -1));

        dsearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                dsearchKeyReleased(evt);
            }
        });
        getContentPane().add(dsearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 80, 261, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Search by Invoice Num");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 80, -1, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 40, 120, 40));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("Manage Customer Details");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 675, 230, 40));

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/backgrnd1.png"))); // NOI18N
        jLabel26.setText("jLabel25");
        getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 770));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void delevraddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delevraddActionPerformed
        try {
            model.Delivery delivery = readDeliveryFields();
            int result = DeliveryController.addDelivery(delivery);

            if (result == 1) {
                JOptionPane.showMessageDialog(this, "added successfully");
                clearDeliveryFields();
                dTable.setModel(DbUtils.resultSetToTableModel(DeliveryController.getAllDeliveryResultSet()));
            } else {
                JOptionPane.showMessageDialog(this, "Cannot be added");

            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Cannot be added");
            Logger.getLogger(Delivery.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_delevraddActionPerformed

    private void delevrupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delevrupdateActionPerformed
        try {
            model.Delivery delivery = readDeliveryFields();
            int result = DeliveryController.updateDelivery(delivery);

            if (result == 1) {
                JOptionPane.showMessageDialog(this, "updated successfully");
                clearDeliveryFields();
                dTable.setModel(DbUtils.resultSetToTableModel(DeliveryController.getAllDeliveryResultSet()));
            } else {
                JOptionPane.showMessageDialog(this, "Cannot be updated");

            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Cannot be updated");
            Logger.getLogger(Delivery.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_delevrupdateActionPerformed

    private void delevrdeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delevrdeleteActionPerformed
      int x = JOptionPane.showConfirmDialog(null, "Do you want to DELETE this record?");
        if (x == 0) {
        try {
            model.Delivery delivery = readDeliveryFields();
            int result = DeliveryController.deleteDelivery(delivery);

            if (result == 1) {
                JOptionPane.showMessageDialog(this, "deleted successfully");
                clearDeliveryFields();
                dTable.setModel(DbUtils.resultSetToTableModel(DeliveryController.getAllDeliveryResultSet()));
            } else {
                JOptionPane.showMessageDialog(this, "Cannot be deleted");

            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Cannot be deleted");
            Logger.getLogger(Delivery.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
    }//GEN-LAST:event_delevrdeleteActionPerformed

    private void delevrcfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delevrcfActionPerformed
        clearDeliveryFields();
    }//GEN-LAST:event_delevrcfActionPerformed

    private void doncashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doncashActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_doncashActionPerformed

    private void ddeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ddeliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ddeliActionPerformed

    private void dTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dTableMouseClicked
        if (dTable.getSelectedRowCount() == 1) {

            delivid.setText(dTable.getValueAt(dTable.getSelectedRow(), 0).toString());
            ditemcode.setText(dTable.getValueAt(dTable.getSelectedRow(), 1).toString());
            ditemname.setText(dTable.getValueAt(dTable.getSelectedRow(), 2).toString());
            dqty.setText(dTable.getValueAt(dTable.getSelectedRow(), 3).toString());
            if (dTable.getValueAt(dTable.getSelectedRow(), 4).toString().equals(Constants.DELIVERY_PAYMENT_PAID)) {
                ddaid.setSelected(true);
            } else {
                doncash.setSelected(true);

            }
            daddress.setText(dTable.getValueAt(dTable.getSelectedRow(), 5).toString());
            if (dTable.getValueAt(dTable.getSelectedRow(), 6).toString().equals(Constants.DELIVERY_STATUS_DELIVERED)) {
                delevradd.setSelected(true);
            } else {
                dpen.setSelected(true);

            }
            dinvoiceid.setText(dTable.getValueAt(dTable.getSelectedRow(), 7).toString());
            dcustid.setText(dTable.getValueAt(dTable.getSelectedRow(), 8).toString());

//               
//               
        }
    }//GEN-LAST:event_dTableMouseClicked

    private void dsearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dsearchKeyReleased
        try {
            dTable.setModel(DbUtils.resultSetToTableModel(DeliveryController.searchDeliveryByInvoiceID(dsearch.getText())));
        } catch (SQLException ex) {
            Logger.getLogger(Delivery.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_dsearchKeyReleased

    private void dqtyKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dqtyKeyReleased
         if(!ValidationChecker.isInteger(dqty.getText()) && !dqty.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Please enter a valid quantity");
        }
    }//GEN-LAST:event_dqtyKeyReleased

    private void dinvoiceidKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dinvoiceidKeyReleased
         if(!ValidationChecker.isInteger(dinvoiceid.getText()) && !dinvoiceid.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Please enter integers only");
        }
    }//GEN-LAST:event_dinvoiceidKeyReleased

    private void dqtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dqtyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dqtyActionPerformed

    private void MapdeliverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MapdeliverActionPerformed
      
        try {
            
            String URL ="https://www.google.lk/maps?source=tldsi&hl=en";
            java.awt.Desktop.getDesktop().browse(java.net.URI.create(URL));
            
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    

    }//GEN-LAST:event_MapdeliverActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Payment pay = new Payment();
        pay.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Customer cus = new Customer();
        cus.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Delivery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Delivery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Delivery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Delivery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Delivery().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Donedeleiver;
    private javax.swing.JButton Mapdeliver;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTable dTable;
    private javax.swing.JTextArea daddress;
    private javax.swing.JTextField dcustid;
    private javax.swing.JRadioButton ddaid;
    private javax.swing.JRadioButton ddeli;
    private javax.swing.JButton delevradd;
    private javax.swing.JButton delevrcf;
    private javax.swing.JButton delevrdelete;
    private javax.swing.JButton delevrupdate;
    private javax.swing.JTextField delivid;
    private javax.swing.JTextField dinvoiceid;
    private javax.swing.JTextField ditemcode;
    private javax.swing.JTextField ditemname;
    private javax.swing.JRadioButton doncash;
    private javax.swing.JRadioButton dpen;
    private javax.swing.JTextField dqty;
    private javax.swing.JTextField dsearch;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables

    private model.Delivery readDeliveryFields() {
        String id = delivid.getText();
        String code = ditemcode.getText();
        String name = ditemname.getText();
        Integer qty = new Integer(dqty.getText());
        Integer invoiceId = new Integer(dinvoiceid.getText());
        String customer = dcustid.getText();
        String address = daddress.getText();
        String status = ddeli.isSelected() ? Constants.DELIVERY_STATUS_DELIVERED : Constants.DELIVERY_STATUS_PENDING;
        String payment = ddaid.isSelected() ? Constants.DELIVERY_PAYMENT_PAID : Constants.DELIVERY_STATUS_ON_CASH;

        model.Delivery delivery = new model.Delivery(id, code, name, qty, payment, address, status, invoiceId, customer);
        return delivery;
    }

    private void clearDeliveryFields() {

        delivid.setText("");
        ditemcode.setText("");
        ditemname.setText("");
        dqty.setText("");
        dinvoiceid.setText("");
        dcustid.setText("");
        daddress.setText("");
        ddeli.setSelected(true);
        ddaid.setSelected(true);

    }
}
