/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfa;

import bill.Payment;
import bsmanagementsystem.MainPage;

/**
 *
 * @author Rashan
 */
public class REsource extends javax.swing.JInternalFrame {

    /**
     * Creates new form REsource
     */
    public REsource() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        manre = new javax.swing.JButton();
        addre = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(1366, 768));
        setMinimumSize(new java.awt.Dimension(1366, 768));
        setPreferredSize(new java.awt.Dimension(1366, 768));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        manre.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        manre.setText("Manage Resources");
        manre.setMaximumSize(new java.awt.Dimension(216, 54));
        manre.setMinimumSize(new java.awt.Dimension(216, 54));
        manre.setPreferredSize(new java.awt.Dimension(216, 54));
        manre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manreActionPerformed(evt);
            }
        });
        getContentPane().add(manre, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 350, 250, 61));

        addre.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        addre.setText("Add Resources");
        addre.setMaximumSize(new java.awt.Dimension(216, 54));
        addre.setMinimumSize(new java.awt.Dimension(216, 54));
        addre.setPreferredSize(new java.awt.Dimension(216, 54));
        addre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addreActionPerformed(evt);
            }
        });
        getContentPane().add(addre, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 350, 250, 61));

        jButton8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton8.setText("Back");
        jButton8.setMaximumSize(new java.awt.Dimension(188, 54));
        jButton8.setMinimumSize(new java.awt.Dimension(188, 54));
        jButton8.setPreferredSize(new java.awt.Dimension(188, 54));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1177, 110, 140, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1350, 730));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void manreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manreActionPerformed
        AddResource add = new AddResource();

        add.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_manreActionPerformed

    private void addreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addreActionPerformed
        Resource_Management manag = new Resource_Management();

        manag.setVisible(true);
        this.dispose();
                           
    }//GEN-LAST:event_addreActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        new MainPage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton8ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addre;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton manre;
    // End of variables declaration//GEN-END:variables
}
