/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfa;

import Codes.ValidationChecker;
import controller.EquipmentManageController;
import controller.FualRoundsController;
import controller.LeasedVehicleManageController;
import controller.OtherResourcesManageController;
import controller.VehicleController;
import controller.VehicleRepairsController;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import model.EquipmentManage;
import model.FualRounds;
import model.LeasedVehicleManage;
import model.OtherResourceManage;
import model.Vehicle;
import model.VehicleRepair;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Sandun
 */
public class Resource_Management extends javax.swing.JFrame {

    /**
     * Creates new form Resource_Management
     */
    public Resource_Management() {
        try {
            initComponents();
            ftable.setModel(DbUtils.resultSetToTableModel(FualRoundsController.getAllFualRoundsAsResultSet()));
            eqTable.setModel(DbUtils.resultSetToTableModel(EquipmentManageController.getAllEquipmentAsResultSet()));
            vTable.setModel(DbUtils.resultSetToTableModel(VehicleRepairsController.getAllRepairsAsResultSet()));
            lvTable.setModel(DbUtils.resultSetToTableModel(LeasedVehicleManageController.getAllLeasedVehicleManageAsResultSet()));
        } catch (SQLException ex) {
            Logger.getLogger(Resource_Management.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        vid = new javax.swing.JTextField();
        vdes = new javax.swing.JTextField();
        vdate = new com.toedter.calendar.JDateChooser();
        vcost = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        vTable = new javax.swing.JTable();
        addrepair = new javax.swing.JButton();
        updaterepair = new javax.swing.JButton();
        deleterepair = new javax.swing.JButton();
        cfrepair = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lvid = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        lvTable = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        lvNextDate = new com.toedter.calendar.JDateChooser();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lvPaymentDate = new com.toedter.calendar.JDateChooser();
        jLabel18 = new javax.swing.JLabel();
        lvPayAmount = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        lvRemaining = new javax.swing.JTextField();
        calculateRemaining = new javax.swing.JButton();
        lvFullyPaid = new javax.swing.JRadioButton();
        jLabel27 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        ftable = new javax.swing.JTable();
        addfualround = new javax.swing.JButton();
        updatefualround = new javax.swing.JButton();
        deletefualround = new javax.swing.JButton();
        cffualround = new javax.swing.JButton();
        fvid = new javax.swing.JTextField();
        fcost = new javax.swing.JTextField();
        litprice = new javax.swing.JTextField();
        tliters = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        fdate = new com.toedter.calendar.JDateChooser();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        calliter = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        orId = new javax.swing.JTextField();
        ordes = new javax.swing.JTextField();
        orCost = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        orDate = new com.toedter.calendar.JDateChooser();
        addotherman = new javax.swing.JButton();
        updateotherman = new javax.swing.JButton();
        deleteotherman = new javax.swing.JButton();
        cfotherman = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        orTable = new javax.swing.JTable();
        jLabel29 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        eqid = new javax.swing.JTextField();
        eqDes = new javax.swing.JTextField();
        eqCost = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        eqTable = new javax.swing.JTable();
        eqDate = new com.toedter.calendar.JDateChooser();
        addequipmanage = new javax.swing.JButton();
        updateequipmanage = new javax.swing.JButton();
        deleteequipmanage = new javax.swing.JButton();
        cfequipmanage = new javax.swing.JButton();
        jLabel30 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1366, 768));
        setMinimumSize(new java.awt.Dimension(1366, 768));
        setPreferredSize(new java.awt.Dimension(1366, 768));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.setMaximumSize(new java.awt.Dimension(1366, 768));
        jTabbedPane1.setMinimumSize(new java.awt.Dimension(1366, 768));
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(1366, 768));

        jTabbedPane2.setMaximumSize(new java.awt.Dimension(1366, 768));
        jTabbedPane2.setMinimumSize(new java.awt.Dimension(1366, 768));

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Vehical ID");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 24, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText(" Description");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(264, 24, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Date");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(422, 24, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Cost");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(646, 24, -1, -1));
        jPanel4.add(vid, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 54, 97, -1));
        jPanel4.add(vdes, new org.netbeans.lib.awtextra.AbsoluteConstraints(264, 54, 79, -1));

        vdate.setDateFormatString("yyyy-MM-dd");
        vdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                vdateMouseClicked(evt);
            }
        });
        jPanel4.add(vdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(422, 54, 160, -1));

        vcost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vcostActionPerformed(evt);
            }
        });
        vcost.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                vcostKeyReleased(evt);
            }
        });
        jPanel4.add(vcost, new org.netbeans.lib.awtextra.AbsoluteConstraints(646, 54, 139, -1));

        vTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Vehical ID", "Title Description", "Date", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        vTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                vTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(vTable);

        jPanel4.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 102, 1140, 572));

        addrepair.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        addrepair.setText("Add");
        addrepair.setMaximumSize(new java.awt.Dimension(130, 36));
        addrepair.setMinimumSize(new java.awt.Dimension(130, 36));
        addrepair.setPreferredSize(new java.awt.Dimension(130, 36));
        addrepair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addrepairActionPerformed(evt);
            }
        });
        jPanel4.add(addrepair, new org.netbeans.lib.awtextra.AbsoluteConstraints(1209, 55, -1, -1));

        updaterepair.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        updaterepair.setText("Edit");
        updaterepair.setMaximumSize(new java.awt.Dimension(130, 36));
        updaterepair.setMinimumSize(new java.awt.Dimension(130, 36));
        updaterepair.setPreferredSize(new java.awt.Dimension(130, 36));
        updaterepair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updaterepairActionPerformed(evt);
            }
        });
        jPanel4.add(updaterepair, new org.netbeans.lib.awtextra.AbsoluteConstraints(1209, 109, -1, -1));

        deleterepair.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        deleterepair.setText("Delete");
        deleterepair.setMaximumSize(new java.awt.Dimension(130, 36));
        deleterepair.setMinimumSize(new java.awt.Dimension(130, 36));
        deleterepair.setPreferredSize(new java.awt.Dimension(130, 36));
        deleterepair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleterepairActionPerformed(evt);
            }
        });
        jPanel4.add(deleterepair, new org.netbeans.lib.awtextra.AbsoluteConstraints(1209, 163, -1, -1));

        cfrepair.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cfrepair.setText("Clear Fields");
        cfrepair.setMaximumSize(new java.awt.Dimension(130, 36));
        cfrepair.setMinimumSize(new java.awt.Dimension(130, 36));
        cfrepair.setPreferredSize(new java.awt.Dimension(130, 36));
        jPanel4.add(cfrepair, new org.netbeans.lib.awtextra.AbsoluteConstraints(1209, 217, -1, -1));

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/backgrnd1.png"))); // NOI18N
        jLabel28.setText("jLabel25");
        jPanel4.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 650));

        jTabbedPane2.addTab("Repairs", jPanel4);

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel5.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 53, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Vehicle ID");
        jPanel5.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 55, -1, -1));
        jPanel5.add(lvid, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 53, 123, -1));

        lvTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Vehicle ID", "Payment Date", "Payment amount", "Next payment due date", "Remaining amount", "Fully paid"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        lvTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lvTableMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(lvTable);

        jPanel5.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 22, 947, 442));

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton5.setText("Add");
        jButton5.setMaximumSize(new java.awt.Dimension(130, 36));
        jButton5.setMinimumSize(new java.awt.Dimension(130, 36));
        jButton5.setPreferredSize(new java.awt.Dimension(130, 36));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(423, 504, -1, -1));

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton6.setText("Edit");
        jButton6.setMaximumSize(new java.awt.Dimension(130, 36));
        jButton6.setMinimumSize(new java.awt.Dimension(130, 36));
        jButton6.setPreferredSize(new java.awt.Dimension(130, 36));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(589, 504, -1, -1));

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton7.setText("Delete");
        jButton7.setMaximumSize(new java.awt.Dimension(130, 36));
        jButton7.setMinimumSize(new java.awt.Dimension(130, 36));
        jButton7.setPreferredSize(new java.awt.Dimension(130, 36));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(748, 504, -1, -1));

        jButton8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton8.setText("Clear fields");
        jButton8.setMaximumSize(new java.awt.Dimension(130, 36));
        jButton8.setMinimumSize(new java.awt.Dimension(130, 36));
        jButton8.setPreferredSize(new java.awt.Dimension(130, 36));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(896, 504, -1, -1));

        lvNextDate.setDateFormatString("yyyy-MM-dd");
        jPanel5.add(lvNextDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 213, 90, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Payment Date");
        jPanel5.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 114, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Next payment due Date");
        jPanel5.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 213, -1, -1));

        lvPaymentDate.setDateFormatString("yyyy-MM-dd");
        jPanel5.add(lvPaymentDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 109, 90, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setText("Payment mount");
        jPanel5.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 169, -1, -1));

        lvPayAmount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                lvPayAmountKeyReleased(evt);
            }
        });
        jPanel5.add(lvPayAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 164, 123, -1));

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel24.setText("Remaining amount");
        jPanel5.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 303, -1, -1));

        lvRemaining.setEditable(false);
        jPanel5.add(lvRemaining, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 301, 124, -1));

        calculateRemaining.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        calculateRemaining.setText("Calculate Remaining amount");
        calculateRemaining.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateRemainingActionPerformed(evt);
            }
        });
        jPanel5.add(calculateRemaining, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 258, 274, -1));

        lvFullyPaid.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lvFullyPaid.setText("Fully paid");
        lvFullyPaid.setEnabled(false);
        jPanel5.add(lvFullyPaid, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 353, -1, -1));

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/backgrnd1.png"))); // NOI18N
        jLabel27.setText("jLabel25");
        jPanel5.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 650));

        jTabbedPane2.addTab("Vehicle Lease Details", jPanel5);

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ftable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Vehical ID", "Date", "Cost", "Liter Price", "Total Liters"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ftable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ftableMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(ftable);

        jPanel6.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(383, 50, 940, 388));

        addfualround.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        addfualround.setText("Add");
        addfualround.setMaximumSize(new java.awt.Dimension(130, 36));
        addfualround.setMinimumSize(new java.awt.Dimension(130, 36));
        addfualround.setPreferredSize(new java.awt.Dimension(130, 36));
        addfualround.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addfualroundActionPerformed(evt);
            }
        });
        jPanel6.add(addfualround, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 491, -1, -1));

        updatefualround.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        updatefualround.setText("Edit");
        updatefualround.setMaximumSize(new java.awt.Dimension(130, 36));
        updatefualround.setMinimumSize(new java.awt.Dimension(130, 36));
        updatefualround.setPreferredSize(new java.awt.Dimension(130, 36));
        updatefualround.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatefualroundActionPerformed(evt);
            }
        });
        jPanel6.add(updatefualround, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 491, -1, -1));

        deletefualround.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        deletefualround.setText("Delete");
        deletefualround.setMaximumSize(new java.awt.Dimension(130, 36));
        deletefualround.setMinimumSize(new java.awt.Dimension(130, 36));
        deletefualround.setPreferredSize(new java.awt.Dimension(130, 36));
        deletefualround.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletefualroundActionPerformed(evt);
            }
        });
        jPanel6.add(deletefualround, new org.netbeans.lib.awtextra.AbsoluteConstraints(395, 491, -1, -1));

        cffualround.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cffualround.setText("Clear Fields");
        cffualround.setMaximumSize(new java.awt.Dimension(130, 36));
        cffualround.setMinimumSize(new java.awt.Dimension(130, 36));
        cffualround.setPreferredSize(new java.awt.Dimension(130, 36));
        cffualround.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cffualroundActionPerformed(evt);
            }
        });
        jPanel6.add(cffualround, new org.netbeans.lib.awtextra.AbsoluteConstraints(543, 491, -1, -1));
        jPanel6.add(fvid, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 91, -1));

        fcost.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                fcostKeyReleased(evt);
            }
        });
        jPanel6.add(fcost, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 225, 103, -1));

        litprice.setEditable(false);
        jPanel6.add(litprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 414, 100, -1));

        tliters.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tlitersKeyReleased(evt);
            }
        });
        jPanel6.add(tliters, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 296, 104, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setText("Vehical ID");
        jPanel6.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 50, -1, -1));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel20.setText("Date");
        jPanel6.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 120, -1, -1));

        fdate.setDateFormatString("yyyy-MM-dd");
        jPanel6.add(fdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 150, 122, -1));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel21.setText("Cost");
        jPanel6.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 190, -1, -1));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel22.setText("Liter Price");
        jPanel6.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 393, -1, -1));

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel23.setText("Total Liters");
        jPanel6.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 277, -1, -1));

        calliter.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        calliter.setText("Calculate Liters");
        calliter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calliterActionPerformed(evt);
            }
        });
        jPanel6.add(calliter, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 336, -1, -1));

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/backgrnd1.png"))); // NOI18N
        jLabel26.setText("jLabel25");
        jPanel6.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 650));

        jTabbedPane2.addTab("Vehicle Fuel Rounds", jPanel6);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 768, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Motar Vehicle", jPanel2);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(orId, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 70, 195, -1));

        ordes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ordesActionPerformed(evt);
            }
        });
        jPanel3.add(ordes, new org.netbeans.lib.awtextra.AbsoluteConstraints(278, 70, 190, -1));

        orCost.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                orCostKeyReleased(evt);
            }
        });
        jPanel3.add(orCost, new org.netbeans.lib.awtextra.AbsoluteConstraints(708, 70, 200, -1));

        jLabel14.setText("Resourse ID");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 41, -1, -1));

        jLabel15.setText("Description");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(278, 41, -1, -1));

        jLabel16.setText("Date");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(496, 41, -1, -1));

        jLabel17.setText("Cost");
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(708, 41, -1, -1));

        orDate.setDateFormatString("yyyy-MM-dd");
        jPanel3.add(orDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(496, 70, 164, -1));

        addotherman.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        addotherman.setText("Add");
        addotherman.setMaximumSize(new java.awt.Dimension(130, 36));
        addotherman.setMinimumSize(new java.awt.Dimension(130, 36));
        addotherman.setPreferredSize(new java.awt.Dimension(130, 36));
        addotherman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addothermanActionPerformed(evt);
            }
        });
        jPanel3.add(addotherman, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 96, -1, -1));

        updateotherman.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        updateotherman.setText("Edit");
        updateotherman.setMaximumSize(new java.awt.Dimension(130, 36));
        updateotherman.setMinimumSize(new java.awt.Dimension(130, 36));
        updateotherman.setPreferredSize(new java.awt.Dimension(130, 36));
        updateotherman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateothermanActionPerformed(evt);
            }
        });
        jPanel3.add(updateotherman, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 168, -1, -1));

        deleteotherman.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        deleteotherman.setText("Delete");
        deleteotherman.setMaximumSize(new java.awt.Dimension(130, 36));
        deleteotherman.setMinimumSize(new java.awt.Dimension(130, 36));
        deleteotherman.setPreferredSize(new java.awt.Dimension(130, 36));
        deleteotherman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteothermanActionPerformed(evt);
            }
        });
        jPanel3.add(deleteotherman, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 246, -1, -1));

        cfotherman.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cfotherman.setText("Clear Fileds");
        cfotherman.setMaximumSize(new java.awt.Dimension(130, 36));
        cfotherman.setMinimumSize(new java.awt.Dimension(130, 36));
        cfotherman.setPreferredSize(new java.awt.Dimension(130, 36));
        jPanel3.add(cfotherman, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 325, -1, -1));

        orTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Resource ID", "Description", "Date", "Cost"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        orTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                orTableMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(orTable);

        jPanel3.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 120, 1026, 563));

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/backgrnd1.png"))); // NOI18N
        jLabel29.setText("jLabel25");
        jPanel3.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 690));

        jTabbedPane1.addTab("Building and Lands", jPanel3);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Equipment ID");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 27, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Description");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 27, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Date");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(401, 27, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Cost");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(648, 27, -1, -1));
        jPanel1.add(eqid, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 51, 103, -1));
        jPanel1.add(eqDes, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 51, 105, -1));

        eqCost.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                eqCostKeyReleased(evt);
            }
        });
        jPanel1.add(eqCost, new org.netbeans.lib.awtextra.AbsoluteConstraints(648, 51, 132, -1));

        eqTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Equipment ID", "Description", "Date", "Cost"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        eqTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eqTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(eqTable);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 104, 1149, 583));

        eqDate.setDateFormatString("yyyy-MM-dd");
        jPanel1.add(eqDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(401, 51, 163, -1));

        addequipmanage.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        addequipmanage.setText("Add");
        addequipmanage.setMaximumSize(new java.awt.Dimension(130, 36));
        addequipmanage.setMinimumSize(new java.awt.Dimension(130, 36));
        addequipmanage.setPreferredSize(new java.awt.Dimension(130, 36));
        addequipmanage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addequipmanageActionPerformed(evt);
            }
        });
        jPanel1.add(addequipmanage, new org.netbeans.lib.awtextra.AbsoluteConstraints(1213, 78, -1, -1));

        updateequipmanage.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        updateequipmanage.setText("Edit");
        updateequipmanage.setMaximumSize(new java.awt.Dimension(130, 36));
        updateequipmanage.setMinimumSize(new java.awt.Dimension(130, 36));
        updateequipmanage.setPreferredSize(new java.awt.Dimension(130, 36));
        updateequipmanage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateequipmanageActionPerformed(evt);
            }
        });
        jPanel1.add(updateequipmanage, new org.netbeans.lib.awtextra.AbsoluteConstraints(1213, 132, -1, -1));

        deleteequipmanage.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        deleteequipmanage.setText("Delete");
        deleteequipmanage.setMaximumSize(new java.awt.Dimension(130, 36));
        deleteequipmanage.setMinimumSize(new java.awt.Dimension(130, 36));
        deleteequipmanage.setPreferredSize(new java.awt.Dimension(130, 36));
        deleteequipmanage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteequipmanageActionPerformed(evt);
            }
        });
        jPanel1.add(deleteequipmanage, new org.netbeans.lib.awtextra.AbsoluteConstraints(1213, 186, -1, -1));

        cfequipmanage.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cfequipmanage.setText("Clear Fields");
        cfequipmanage.setMaximumSize(new java.awt.Dimension(130, 36));
        cfequipmanage.setMinimumSize(new java.awt.Dimension(130, 36));
        cfequipmanage.setPreferredSize(new java.awt.Dimension(130, 36));
        jPanel1.add(cfequipmanage, new org.netbeans.lib.awtextra.AbsoluteConstraints(1213, 240, -1, -1));

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/backgrnd1.png"))); // NOI18N
        jLabel30.setText("jLabel25");
        jPanel1.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 680));

        jTabbedPane1.addTab("Equipment", jPanel1);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 1370, 710));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Resource Management ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(626, 16, 220, 30));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 20, 110, 40));

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/backgrnd1.png"))); // NOI18N
        jLabel25.setText("jLabel25");
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ordesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ordesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ordesActionPerformed

    private void calliterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calliterActionPerformed
        try {
            if (!"".equals(fcost.getText()) && !"".equals(tliters.getText())) {
                Float fuelCost = new Float(fcost.getText());
                Float totalLiters = new Float(tliters.getText());
                Float unitprice = fuelCost / totalLiters;
                litprice.setText(unitprice.toString());
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Plase enter valid numbers");
        }
    }//GEN-LAST:event_calliterActionPerformed

    private void addfualroundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addfualroundActionPerformed
        FualRounds fualRounds = readFuelRValues();

        try {
            int result = FualRoundsController.addFualRound(fualRounds);

            if (result == 1) {
                JOptionPane.showMessageDialog(this, "added successfully");
                clearFuelFields();
                ftable.setModel(DbUtils.resultSetToTableModel(FualRoundsController.getAllFualRoundsAsResultSet()));
            } else {
                JOptionPane.showMessageDialog(this, "Cannot be added");

            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Cannot be added");
            Logger.getLogger(Resource_Management.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_addfualroundActionPerformed

    private void ftableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ftableMouseClicked
        if (ftable.getSelectedRowCount() == 1) {
            fvid.setText(ftable.getValueAt(ftable.getSelectedRow(), 0).toString());
            fcost.setText(ftable.getValueAt(ftable.getSelectedRow(), 1).toString());
            ((JTextField)fdate.getDateEditor().getUiComponent()).setText(ftable.getValueAt(ftable.getSelectedRow(), 2).toString());
            tliters.setText(ftable.getValueAt(ftable.getSelectedRow(), 4).toString());
            litprice.setText(ftable.getValueAt(ftable.getSelectedRow(), 3).toString());
        }
    }//GEN-LAST:event_ftableMouseClicked

    private void updatefualroundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatefualroundActionPerformed
        FualRounds fualRounds = readFuelRValues();
        fualRounds.setVehicle_ID(fvid.getText());

        try {
            int result = FualRoundsController.updateFualRound(fualRounds);

            if (result == 1) {
                JOptionPane.showMessageDialog(this, "updated successfully");
                clearFuelFields();
                ftable.setModel(DbUtils.resultSetToTableModel(FualRoundsController.getAllFualRoundsAsResultSet()));
            } else {
                JOptionPane.showMessageDialog(this, "Cannot be updated");

            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Cannot be updated");
            Logger.getLogger(Resource_Management.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_updatefualroundActionPerformed

    private void deletefualroundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletefualroundActionPerformed
        int x = JOptionPane.showConfirmDialog(null, "Do you want to DELETE this record?");
        if (x == 0) {

            FualRounds fualRounds = new FualRounds();
            fualRounds.setVehicle_ID(fvid.getText());

            try {
                int result = FualRoundsController.deleteFualRound(fualRounds);

                if (result == 1) {
                    JOptionPane.showMessageDialog(this, "deleted successfully");
                    clearFuelFields();
                    ftable.setModel(DbUtils.resultSetToTableModel(FualRoundsController.getAllFualRoundsAsResultSet()));
                } else {
                    JOptionPane.showMessageDialog(this, "Cannot be deleted");

                }

            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Cannot be deleted");
                Logger.getLogger(Resource_Management.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_deletefualroundActionPerformed

    private void addequipmanageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addequipmanageActionPerformed
        EquipmentManage equipmentManage = readEquipmentFields();

        try {
            int result = EquipmentManageController.addEquipmentManage(equipmentManage);

            if (result == 1) {
                JOptionPane.showMessageDialog(this, "added successfully");
                clearEquipmentFields();
                eqTable.setModel(DbUtils.resultSetToTableModel(EquipmentManageController.getAllEquipmentAsResultSet()));
            } else {
                JOptionPane.showMessageDialog(this, "Cannot be added");

            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Cannot be added");
            Logger.getLogger(Resource_Management.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_addequipmanageActionPerformed

    private void updateequipmanageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateequipmanageActionPerformed
        EquipmentManage equipmentManage = readEquipmentFields();

        try {
            int result = EquipmentManageController.updateEquipmentManage(equipmentManage);

            if (result == 1) {
                JOptionPane.showMessageDialog(this, "updated successfully");
                clearEquipmentFields();
                eqTable.setModel(DbUtils.resultSetToTableModel(EquipmentManageController.getAllEquipmentAsResultSet()));
            } else {
                JOptionPane.showMessageDialog(this, "Cannot update");

            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Cannot be updated");
            Logger.getLogger(Resource_Management.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_updateequipmanageActionPerformed

    private void deleteequipmanageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteequipmanageActionPerformed

        int x = JOptionPane.showConfirmDialog(null, "Do you want to DELETE this record?");
        if (x == 0) {
            EquipmentManage equipmentManage = new EquipmentManage();
            equipmentManage.setEquipmnt_ID(eqid.getText());

            try {
                int result = EquipmentManageController.deleteEquipmentManage(equipmentManage);

                if (result == 1) {
                    JOptionPane.showMessageDialog(this, "deleted successfully");
                    clearEquipmentFields();
                    eqTable.setModel(DbUtils.resultSetToTableModel(EquipmentManageController.getAllEquipmentAsResultSet()));
                } else {
                    JOptionPane.showMessageDialog(this, "Cannot be deleted");

                }

            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Cannot be deleted");
                Logger.getLogger(Resource_Management.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_deleteequipmanageActionPerformed

    private void eqTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eqTableMouseClicked
        if (eqTable.getSelectedRowCount() == 1) {
            eqid.setText(eqTable.getValueAt(eqTable.getSelectedRow(), 0).toString());
            eqDes.setText(eqTable.getValueAt(eqTable.getSelectedRow(), 1).toString());
            ((JTextField)eqDate.getDateEditor().getUiComponent()).setText(eqTable.getValueAt(eqTable.getSelectedRow(), 2).toString());
//            eqDate.setText(eqTable.getValueAt(eqTable.getSelectedRow(), 2).toString());
            eqCost.setText(eqTable.getValueAt(eqTable.getSelectedRow(), 3).toString());
        }
    }//GEN-LAST:event_eqTableMouseClicked

    private void addothermanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addothermanActionPerformed
        OtherResourceManage otherResourceManage = readOtherResourceFields();

        try {
            int result = OtherResourcesManageController.addOtherResourcesManage(otherResourceManage);

            if (result == 1) {
                JOptionPane.showMessageDialog(this, "added successfully");
                clearOtherResourceFields();
                orTable.setModel(DbUtils.resultSetToTableModel(OtherResourcesManageController.getAllOtherResourceAsResultSet()));
            } else {
                JOptionPane.showMessageDialog(this, "Cannot be added");

            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Cannot be added");
            Logger.getLogger(Resource_Management.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_addothermanActionPerformed

    private void updateothermanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateothermanActionPerformed
        OtherResourceManage otherResourceManage = readOtherResourceFields();

        try {
            int result = OtherResourcesManageController.updateOtherResourcesManage(otherResourceManage);

            if (result == 1) {
                JOptionPane.showMessageDialog(this, "updated successfully");
                clearOtherResourceFields();
                orTable.setModel(DbUtils.resultSetToTableModel(OtherResourcesManageController.getAllOtherResourceAsResultSet()));
            } else {
                JOptionPane.showMessageDialog(this, "Cannot be updated");

            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Cannot be updated");
            Logger.getLogger(Resource_Management.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_updateothermanActionPerformed

    private void deleteothermanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteothermanActionPerformed
        int x = JOptionPane.showConfirmDialog(null, "Do you want to DELETE this record?");
        if (x == 0) {
            OtherResourceManage otherResourceManage = new OtherResourceManage();
            otherResourceManage.setResource_ID(orId.getText());

            try {
                int result = OtherResourcesManageController.deleteOtherResourcesManage(otherResourceManage);

                if (result == 1) {
                    JOptionPane.showMessageDialog(this, "deleted successfully");
                    clearOtherResourceFields();
                    orTable.setModel(DbUtils.resultSetToTableModel(OtherResourcesManageController.getAllOtherResourceAsResultSet()));
                } else {
                    JOptionPane.showMessageDialog(this, "Cannot be deleted");

                }

            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Cannot be deleted");
                Logger.getLogger(Resource_Management.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_deleteothermanActionPerformed

    private void cffualroundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cffualroundActionPerformed
        clearFuelFields();
    }//GEN-LAST:event_cffualroundActionPerformed

    private void addrepairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addrepairActionPerformed
        VehicleRepair vehicleRepair = readVehicleRepairFields();

        try {
            int result = VehicleRepairsController.addVehicleRepairs(vehicleRepair);

            if (result == 1) {
                JOptionPane.showMessageDialog(this, "added successfully");
                clearVehicleRepairFields();
                vTable.setModel(DbUtils.resultSetToTableModel(VehicleRepairsController.getAllRepairsAsResultSet()));
            } else {
                JOptionPane.showMessageDialog(this, "Cannot be added");

            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Cannot be added");
            Logger.getLogger(Resource_Management.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_addrepairActionPerformed

    private void vTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vTableMouseClicked
        if (vTable.getSelectedRowCount() == 1) {
            vid.setText(vTable.getValueAt(vTable.getSelectedRow(), 0).toString());
            vdes.setText(vTable.getValueAt(vTable.getSelectedRow(), 1).toString());
             ((JTextField)vdate.getDateEditor().getUiComponent()).setText(vTable.getValueAt(vTable.getSelectedRow(), 2).toString());
            vcost.setText(vTable.getValueAt(vTable.getSelectedRow(), 3).toString());
        }
    }//GEN-LAST:event_vTableMouseClicked

    private void updaterepairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updaterepairActionPerformed
        VehicleRepair vehicleRepair = readVehicleRepairFields();

        try {
            int result = VehicleRepairsController.updateVehicleRepairs(vehicleRepair);

            if (result == 1) {
                JOptionPane.showMessageDialog(this, "updated successfully");
                clearVehicleRepairFields();
                vTable.setModel(DbUtils.resultSetToTableModel(VehicleRepairsController.getAllRepairsAsResultSet()));
            } else {
                JOptionPane.showMessageDialog(this, "Cannot be updated");

            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Cannot be updated");
            Logger.getLogger(Resource_Management.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_updaterepairActionPerformed

    private void deleterepairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleterepairActionPerformed
        int x = JOptionPane.showConfirmDialog(null, "Do you want to DELETE this record?");
        if (x == 0) {
            VehicleRepair vehicleRepair = new VehicleRepair();
            vehicleRepair.setVehicle_ID(vid.getText());

            try {
                int result = VehicleRepairsController.deleteVehicleRepairs(vehicleRepair);

                if (result == 1) {
                    JOptionPane.showMessageDialog(this, "deleted successfully");
                    clearVehicleRepairFields();
                    vTable.setModel(DbUtils.resultSetToTableModel(VehicleRepairsController.getAllRepairsAsResultSet()));
                } else {
                    JOptionPane.showMessageDialog(this, "Cannot be deleted");

                }

            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Cannot be deleted");
                Logger.getLogger(Resource_Management.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_deleterepairActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        try {
            LeasedVehicleManage leasedVehicleManage = readLeasedFields();
            ResultSet rs = LeasedVehicleManageController.searchVehicleByID(leasedVehicleManage.getVehicle_ID());
            if (rs.next()) {
                int result = LeasedVehicleManageController.updateLeasedVehicleManage(leasedVehicleManage);

                if (result == 1) {
                    JOptionPane.showMessageDialog(this, "added successfully");
                    clearLeasedFields();
                    lvTable.setModel(DbUtils.resultSetToTableModel(LeasedVehicleManageController.getAllLeasedVehicleManageAsResultSet()));
                } else {
                    JOptionPane.showMessageDialog(this, "Cannot be added");

                }

            } else {

                int result = LeasedVehicleManageController.addLeasedVehicleManage(leasedVehicleManage);

                if (result == 1) {
                    JOptionPane.showMessageDialog(this, "added successfully");
                    clearLeasedFields();
                    lvTable.setModel(DbUtils.resultSetToTableModel(LeasedVehicleManageController.getAllLeasedVehicleManageAsResultSet()));
                } else {
                    JOptionPane.showMessageDialog(this, "Cannot be added");

                }

            }

        } catch (SQLException ex) {
            Logger.getLogger(Resource_Management.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton5ActionPerformed

    private void calculateRemainingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateRemainingActionPerformed
        calculateRemaingAmount();

    }//GEN-LAST:event_calculateRemainingActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        try {
            LeasedVehicleManage leasedVehicleManage = readLeasedFields();
            ResultSet rs = LeasedVehicleManageController.searchVehicleByID(leasedVehicleManage.getVehicle_ID());
            if (rs.next()) {
                int result = LeasedVehicleManageController.updateLeasedVehicleManage(leasedVehicleManage);

                if (result == 1) {
                    JOptionPane.showMessageDialog(this, "updated successfully");
                    clearLeasedFields();
                    lvTable.setModel(DbUtils.resultSetToTableModel(LeasedVehicleManageController.getAllLeasedVehicleManageAsResultSet()));
                } else {
                    JOptionPane.showMessageDialog(this, "Cannot be added");

                }

            }else{
                 JOptionPane.showMessageDialog(this, "Please enter a valid Vehicle number");
                
            }
        } catch (SQLException ex) {
            Logger.getLogger(Resource_Management.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void lvTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lvTableMouseClicked
         if (lvTable.getSelectedRowCount() == 1) {
            lvid.setText(lvTable.getValueAt(lvTable.getSelectedRow(), 0).toString());
            ((JTextField)lvPaymentDate.getDateEditor().getUiComponent()).setText(lvTable.getValueAt(lvTable.getSelectedRow(), 1).toString());
            lvPayAmount.setText(lvTable.getValueAt(lvTable.getSelectedRow(), 2).toString());
            ((JTextField)lvNextDate.getDateEditor().getUiComponent()).setText(lvTable.getValueAt(lvTable.getSelectedRow(), 3).toString());
            lvRemaining.setText(lvTable.getValueAt(lvTable.getSelectedRow(), 4).toString());
            lvFullyPaid.setSelected(lvTable.getValueAt(lvTable.getSelectedRow(), 4).toString().equals("true"));
        }
    }//GEN-LAST:event_lvTableMouseClicked

    private void orTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_orTableMouseClicked
        if (orTable.getSelectedRowCount() == 1) {
            orId.setText(orTable.getValueAt(orTable.getSelectedRow(), 0).toString());
            ordes.setText(orTable.getValueAt(orTable.getSelectedRow(), 1).toString());
            ((JTextField)orDate.getDateEditor().getUiComponent()).setText(orTable.getValueAt(orTable.getSelectedRow(), 2).toString());
            orCost.setText(orTable.getValueAt(orTable.getSelectedRow(), 3).toString());
        }
    }//GEN-LAST:event_orTableMouseClicked

    private void vdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vdateMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_vdateMouseClicked

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
         int x = JOptionPane.showConfirmDialog(null, "Do you want to DELETE this record?");
        if (x == 0) {
            LeasedVehicleManage leasedVehicleManage = new LeasedVehicleManage();
            leasedVehicleManage.setVehicle_ID(lvid.getText());

            try {
                int result = LeasedVehicleManageController.deleteLeasedVehicleManage(leasedVehicleManage);

                if (result == 1) {
                    JOptionPane.showMessageDialog(this, "deleted successfully");
                    clearLeasedFields();
                    lvTable.setModel(DbUtils.resultSetToTableModel(LeasedVehicleManageController.getAllLeasedVehicleManageAsResultSet()));
                } else {
                    JOptionPane.showMessageDialog(this, "Cannot be deleted");

                }

            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Cannot be deleted");
                Logger.getLogger(Resource_Management.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        clearLeasedFields();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void eqCostKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_eqCostKeyReleased
        if(!ValidationChecker.isDecimal(eqCost.getText()) && !eqCost.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Please enter a valid cost");
        }
    }//GEN-LAST:event_eqCostKeyReleased

    private void vcostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vcostActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vcostActionPerformed

    private void vcostKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_vcostKeyReleased
        if(!ValidationChecker.isDecimal(vcost.getText()) && !vcost.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Please enter a valid cost");
        }
    }//GEN-LAST:event_vcostKeyReleased

    private void lvPayAmountKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lvPayAmountKeyReleased
        if(!ValidationChecker.isDecimal(lvPayAmount.getText()) && !lvPayAmount.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Please enter a valid amount");
        }
    }//GEN-LAST:event_lvPayAmountKeyReleased

    private void fcostKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fcostKeyReleased
        if(!ValidationChecker.isDecimal(fcost.getText()) && !fcost.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Please enter a valid cost");
        }
    }//GEN-LAST:event_fcostKeyReleased

    private void tlitersKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tlitersKeyReleased
        if(!ValidationChecker.isDecimal(tliters.getText()) && !tliters.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Please enter a valid number");
        }
    }//GEN-LAST:event_tlitersKeyReleased

    private void orCostKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_orCostKeyReleased
        if(!ValidationChecker.isDecimal(orCost.getText()) && !orCost.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Please enter a valid cost");
        }
    }//GEN-LAST:event_orCostKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new RESource1().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Resource_Management.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Resource_Management.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Resource_Management.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Resource_Management.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Resource_Management().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addequipmanage;
    private javax.swing.JButton addfualround;
    private javax.swing.JButton addotherman;
    private javax.swing.JButton addrepair;
    private javax.swing.JButton calculateRemaining;
    private javax.swing.JButton calliter;
    private javax.swing.JButton cfequipmanage;
    private javax.swing.JButton cffualround;
    private javax.swing.JButton cfotherman;
    private javax.swing.JButton cfrepair;
    private javax.swing.JButton deleteequipmanage;
    private javax.swing.JButton deletefualround;
    private javax.swing.JButton deleteotherman;
    private javax.swing.JButton deleterepair;
    private javax.swing.JTextField eqCost;
    private com.toedter.calendar.JDateChooser eqDate;
    private javax.swing.JTextField eqDes;
    private javax.swing.JTable eqTable;
    private javax.swing.JTextField eqid;
    private javax.swing.JTextField fcost;
    private com.toedter.calendar.JDateChooser fdate;
    private javax.swing.JTable ftable;
    private javax.swing.JTextField fvid;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextField litprice;
    private javax.swing.JRadioButton lvFullyPaid;
    private com.toedter.calendar.JDateChooser lvNextDate;
    private javax.swing.JTextField lvPayAmount;
    private com.toedter.calendar.JDateChooser lvPaymentDate;
    private javax.swing.JTextField lvRemaining;
    private javax.swing.JTable lvTable;
    private javax.swing.JTextField lvid;
    private javax.swing.JTextField orCost;
    private com.toedter.calendar.JDateChooser orDate;
    private javax.swing.JTextField orId;
    private javax.swing.JTable orTable;
    private javax.swing.JTextField ordes;
    private javax.swing.JTextField tliters;
    private javax.swing.JButton updateequipmanage;
    private javax.swing.JButton updatefualround;
    private javax.swing.JButton updateotherman;
    private javax.swing.JButton updaterepair;
    private javax.swing.JTable vTable;
    private javax.swing.JTextField vcost;
    private com.toedter.calendar.JDateChooser vdate;
    private javax.swing.JTextField vdes;
    private javax.swing.JTextField vid;
    // End of variables declaration//GEN-END:variables

    private FualRounds readFuelRValues() {
        String enddate = ((JTextField)fdate.getDateEditor().getUiComponent()).getText();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        Float fuelCost = new Float(fcost.getText());
        Float totalLiters = new Float(tliters.getText());
        Float literCost = new Float(litprice.getText());
        String vehicleId = fvid.getText();

        FualRounds fuaal = new FualRounds(vehicleId, fuelCost, enddate, literCost, totalLiters);

        return fuaal;
    }

    private void clearFuelFields() {
        fcost.setText("");
        tliters.setText("");
        litprice.setText("");
        fvid.setText("");
    }

    private EquipmentManage readEquipmentFields() {
        String eDate =  ((JTextField)eqDate.getDateEditor().getUiComponent()).getText();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        Float cost = new Float(eqCost.getText());

        EquipmentManage equipmentManage = new EquipmentManage(eqid.getText(), eqDes.getText(), eDate, cost);

        return equipmentManage;
    }

    private void clearEquipmentFields() {
        eqid.setText("");
        eqCost.setText("");
        eqDes.setText("");
//        eqDate.setText("");
    }

    private OtherResourceManage readOtherResourceFields() {
        String eDate =  ((JTextField)orDate.getDateEditor().getUiComponent()).getText();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        Float cost = new Float(orCost.getText());

        OtherResourceManage otherResource = new OtherResourceManage(orId.getText(), ordes.getText(),eDate, cost);

        return otherResource;
    }

    private void clearOtherResourceFields() {
        orId.setText("");
        eqCost.setText("");
        ordes.setText("");
//        eqDate.setText("");
    }

    private VehicleRepair readVehicleRepairFields() {
        String eDate = ((JTextField)vdate.getDateEditor().getUiComponent()).getText();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        Float cost = new Float(vcost.getText());

        VehicleRepair vehicleRepair = new VehicleRepair(vid.getText(), cost, eDate, vdes.getText());

        return vehicleRepair;
    }

    private void clearVehicleRepairFields() {
        vid.setText("");
        vcost.setText("");
        vdes.setText("");
//        eqDate.setText("");
    }

    private LeasedVehicleManage readLeasedFields() {
        String vId = lvid.getText();
        Float pAmount = new Float(lvPayAmount.getText());
        Date eDate = lvPaymentDate.getCalendar().getTime();
        String paymentDate =  ((JTextField)lvPaymentDate.getDateEditor().getUiComponent()).getText();
        String nextDate =  ((JTextField)lvNextDate.getDateEditor().getUiComponent()).getText();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        Float remainingAmount = new Float(lvRemaining.getText());
        Boolean fullypaid = lvFullyPaid.isSelected();

        LeasedVehicleManage leasedVehicleManage = new LeasedVehicleManage(vId, paymentDate, pAmount, nextDate, remainingAmount, fullypaid);
        return leasedVehicleManage;
    }

    private void clearLeasedFields() {
        lvid.setText("");
        lvPayAmount.setText("");
        lvRemaining.setText("");
        lvFullyPaid.setSelected(false);

    }

    private void calculateRemaingAmount() {
        try {
            String vehicleID = lvid.getText();
            ResultSet rs = LeasedVehicleManageController.searchVehicleByID(vehicleID);
            if (rs.next()) {
                Float remaining = new Float(rs.getFloat("remaining_amount") - new Float(lvPayAmount.getText()));
                lvRemaining.setText(remaining.toString());
                if (remaining <= 0) {
                    lvFullyPaid.setSelected(true);
                }else{
                    lvFullyPaid.setSelected(false);
                }
            } else {
                Vehicle vehicle = VehicleController.getVehicleByID(vehicleID);
                if (vehicle != null) {
                    Float remaining = new Float(vehicle.getVehicle_cost() - new Float(lvPayAmount.getText()));
                    lvRemaining.setText(remaining.toString());
                    if (remaining <= 0) {
                        lvFullyPaid.setSelected(true);
                    }else{
                    lvFullyPaid.setSelected(false);
                     }
                } else {
                    JOptionPane.showMessageDialog(this, "Please enter a valid Vehicle number");
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(Resource_Management.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
