/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces_hard;
import hard1.*;
import hard1.PendingOrde;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.Instant;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author DUL
 */
public class orders extends javax.swing.JFrame {

    /**
     * Creates new form orders
     */
    public orders() {
        initComponents();
    }

   public void refresh(List list)
           
   {
    org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, rordersList, jTable3);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${item}"));
        columnBinding.setColumnName("Item");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${payment}"));
        columnBinding.setColumnName("Payment");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${billnum}"));
        columnBinding.setColumnName("Billnum");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${rmarks}"));
        columnBinding.setColumnName("Rmarks");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${discription}"));
        columnBinding.setColumnName("Discription");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${rdate}"));
        columnBinding.setColumnName("Rdate");
        columnBinding.setColumnClass(java.util.Date.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${suplier}"));
        columnBinding.setColumnName("Suplier");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${POrderID}"));
        columnBinding.setColumnName("POrder ID");
        columnBinding.setColumnClass(Integer.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        
        jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, pendingOrdeList1, jTable2);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${description}"));
        columnBinding.setColumnName("Description");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${item}"));
        columnBinding.setColumnName("Item");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${suplier}"));
        columnBinding.setColumnName("Suplier");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${POrderID}"));
        columnBinding.setColumnName("POrder ID");
        columnBinding.setColumnClass(Integer.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
   
   }
   
 
       
   
   
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        hard1PUEntityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("hard1PU").createEntityManager();
        pendingOrdeQuery = java.beans.Beans.isDesignTime() ? null : hard1PUEntityManager.createQuery("SELECT p FROM PendingOrde p");
        pendingOrdeList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : pendingOrdeQuery.getResultList();
        rordersQuery = java.beans.Beans.isDesignTime() ? null : hard1PUEntityManager.createQuery("SELECT r FROM Rorders r");
        rordersList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : rordersQuery.getResultList();
        rordersQuery1 = java.beans.Beans.isDesignTime() ? null : hard1PUEntityManager.createQuery("SELECT r FROM Rorders r");
        rordersList1 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : rordersQuery1.getResultList();
        pendingOrdeQuery1 = java.beans.Beans.isDesignTime() ? null : hard1PUEntityManager.createQuery("SELECT p FROM PendingOrde p");
        pendingOrdeList1 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : pendingOrdeQuery1.getResultList();
        rordersQuery2 = java.beans.Beans.isDesignTime() ? null : hard1PUEntityManager.createQuery("SELECT r FROM Rorders r");
        rordersList2 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : rordersQuery2.getResultList();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        Box11 = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        item = new javax.swing.JTextField();
        tpay = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        dis1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        dis2 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        bnum = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        date = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        PorderId = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1366, 700));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Trajan Pro", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("PENDING ORDERS");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(229, 72, 198, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ORDERS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 20, -1, -1));

        jLabel3.setFont(new java.awt.Font("Trajan Pro", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("RECIVED ORDERS");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(612, 72, 191, -1));

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, rordersList, jTable3);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${item}"));
        columnBinding.setColumnName("Item");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${payment}"));
        columnBinding.setColumnName("Payment");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${billnum}"));
        columnBinding.setColumnName("Billnum");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${rmarks}"));
        columnBinding.setColumnName("Rmarks");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${discription}"));
        columnBinding.setColumnName("Discription");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${rdate}"));
        columnBinding.setColumnName("Rdate");
        columnBinding.setColumnClass(java.util.Date.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${suplier}"));
        columnBinding.setColumnName("Suplier");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${POrderID}"));
        columnBinding.setColumnName("POrder ID");
        columnBinding.setColumnClass(Integer.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        jScrollPane1.setViewportView(jTable3);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(582, 109, 650, 261));

        jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, pendingOrdeList1, jTable2);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${description}"));
        columnBinding.setColumnName("Description");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${item}"));
        columnBinding.setColumnName("Item");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${suplier}"));
        columnBinding.setColumnName("Suplier");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${POrderID}"));
        columnBinding.setColumnName("POrder ID");
        columnBinding.setColumnClass(Integer.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        jScrollPane2.setViewportView(jTable2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 109, 503, 261));

        jLabel7.setFont(new java.awt.Font("Trajan Pro", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("CONFIRM PENDING ORDERS");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(344, 398, -1, -1));

        Box11.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        Box11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Box11ActionPerformed(evt);
            }
        });
        getContentPane().add(Box11, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 480, 170, -1));

        jLabel4.setText("SUPPLIER :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 480, 71, -1));

        jLabel5.setText("ITEM :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 520, 55, -1));
        getContentPane().add(item, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 520, 170, 20));
        getContentPane().add(tpay, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 552, 170, -1));

        jLabel10.setText("TOTEL PAYMENT:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 558, -1, -1));

        jButton1.setText("SUBMIT RECIVED ORDER");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 588, 211, -1));

        dis1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dis1ActionPerformed(evt);
            }
        });
        getContentPane().add(dis1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 470, 267, 98));

        jLabel6.setText("DISCRIPTION (ABOUT ORDER) :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 450, -1, -1));

        jButton2.setText("BACK TO MENU");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(486, 588, 224, -1));
        getContentPane().add(dis2, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 470, 233, 98));

        jLabel11.setText("DISCRIPTION (ABOUT RECEIVED) :");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 450, -1, -1));

        jButton3.setText("BACK TO SUPPLIERS");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(817, 588, 225, -1));
        getContentPane().add(bnum, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 540, 104, -1));

        jLabel9.setText("BILLING NUMBER:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 520, -1, -1));

        date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateActionPerformed(evt);
            }
        });
        getContentPane().add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 490, 104, -1));

        jLabel8.setText("RECEIVED DATE :");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 450, 86, -1));
        getContentPane().add(PorderId, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 450, 170, 20));

        jLabel13.setText("SUP ID:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 450, 60, 20));

        jLabel12.setText("mm/dd/yy");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 470, 100, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/subbg.jpeg"))); // NOI18N
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -6, 1410, 930));

        bindingGroup.bind();

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Box11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Box11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Box11ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
            Rorders x =new Rorders();
           
            
        
        x.setSuplier((String) Box11.getSelectedItem());
        x.setItem(item.getText());
        //x.setDescripti(dis1.getText());
        x.setDiscription(dis1.getText());
        x.setPayment(Integer.parseInt(tpay.getText()));
        x.setRmarks(dis2.getText());
       // x.getRdate(date);
        DateFormat df =new SimpleDateFormat("mm/dd/yyyy");
        try {
            x.setRdate(df.parse(date.getText()));
        } catch (ParseException ex) {
            Logger.getLogger(orders.class.getName()).log(Level.SEVERE, null, ex);
        }
        x.setBillnum(Integer.parseInt(bnum.getText()));
        x.setPOrderID(Integer.parseInt(PorderId.getText()));
        
    
        
        hard1PUEntityManager.getTransaction().begin();
        hard1PUEntityManager.persist(x);
        hard1PUEntityManager.getTransaction().commit();
        rordersList.clear();
        rordersList = rordersQuery.getResultList();
        refresh(rordersList);
        
        PendingOrde p=new PendingOrde();
        p=hard1PUEntityManager.find(PendingOrde.class,Integer.parseInt(PorderId.getText()));
        
        hard1PUEntityManager.getTransaction().begin();
        hard1PUEntityManager.remove(p);
        hard1PUEntityManager.getTransaction().commit();
        pendingOrdeList1.clear();
        pendingOrdeList1 = pendingOrdeQuery.getResultList();
        refresh(pendingOrdeList1);
        
        
        
        JOptionPane.showMessageDialog(this, "Order added");
    

    }//GEN-LAST:event_jButton1ActionPerformed

    private void dis1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dis1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dis1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        supplirs m1= new supplirs();
        m1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void dateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(orders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(orders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(orders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(orders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new orders().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox Box11;
    private javax.swing.JTextField PorderId;
    private javax.swing.JTextField bnum;
    private javax.swing.JFormattedTextField date;
    private javax.swing.JTextField dis1;
    private javax.swing.JTextField dis2;
    private javax.persistence.EntityManager hard1PUEntityManager;
    private javax.swing.JTextField item;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private java.util.List<hard1.PendingOrde> pendingOrdeList;
    private java.util.List<hard1.PendingOrde> pendingOrdeList1;
    private javax.persistence.Query pendingOrdeQuery;
    private javax.persistence.Query pendingOrdeQuery1;
    private java.util.List<hard1.Rorders> rordersList;
    private java.util.List<hard1.Rorders> rordersList1;
    private java.util.List<hard1.Rorders> rordersList2;
    private javax.persistence.Query rordersQuery;
    private javax.persistence.Query rordersQuery1;
    private javax.persistence.Query rordersQuery2;
    private javax.swing.JTextField tpay;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
