/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import database.DBconnect;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author ASUS
 */
public class v_balance_stock_valuation extends javax.swing.JFrame {

    Connection con=null;
    PreparedStatement pst=null;
    ResultSet rs=null;
    /**
     * Creates new form v_balance_stock_valuation
     */
    public v_balance_stock_valuation() {
        initComponents();
          //kodi connect DB
        con = DBconnect.connect();
        
        //for load the result table
        tableload();
    }
    
    public void clear1()
    {
         ptypebox.setSelectedIndex(0);
    }
    
    public void clear2()
    {
            rs=null;
         jTable1.setModel(DbUtils.resultSetToTableModel(rs));
    }
    
    public void tableload()
    {
        try {
        String sql="SELECT ProductID,ProductName,ProductType,Manufacture,Quantity,CostPerUnit FROM products ";
        
        pst = con.prepareStatement(sql);
        rs =pst.executeQuery();
        
        xyz.setModel(DbUtils.resultSetToTableModel(rs));
        
        }
        catch (SQLException e)
        {
        }
        
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        ptypebox = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        xyz = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        qtybox = new javax.swing.JLabel();
        cpubox = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        pnamebox = new javax.swing.JLabel();
        manubox = new javax.swing.JLabel();
        pidbox = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1366, 768));
        setMinimumSize(new java.awt.Dimension(1366, 768));
        setSize(new java.awt.Dimension(1366, 768));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setText("BACK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 660, 120, 46));

        ptypebox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select a Product Type", "Adhesives", "Glue", "Tape", "Adhesive Applicators", "Adhesive Removers", "All-Purpose Glue", "Super Glue", "Construction Glue", "Contact Cements", "Duct & Cloth Tape", "Epoxy Adhesives", "Floor & Tile Adhesives", "Glass & Mirror Adhesives", "Masking Paper", "Masking Tape", "Plastic Tapes", "Repair Adhesives", "Velcro", "Vinyl / Pool Adhesives", "Wood Glue", "Acrylic Sheeting", "Ceiling Material", "Concrete / Blacktop / Sand", "Deck & Roofing Fasteners", "Fastener Kits", "Insulation", "Polyethelene Sheeting", "Metal Goods", "Sandpaper & Steel Wool", "Wood Dowels", "Wood Products", "Wood Repair", "Wood Shims / Specialty Products", "Ventilation", "Hardware Cloth", "Decorator Brick / Accessories", "Rails & Accessories", "Hobby Materials", "Synthetic Filament Rope", "Rope", "Chain & Cable Fittings", "Clothesline", "Sashes, Blinds & Drapery Cord", "Straps, Clamps & Tightener", "Twine & String", "Carbon Monoxide Detectors", "Smoke Detectors", "Child Safety", "Door Locks & Handles", "Specialty Safety & Security Items", "Safety Test Kits", "Fire Extinguishers", "Home Security System", "Safes", "Security Bars", "Paint", "Primers", "Wood Stains, Sealers & Clear Topcoats", "Concrete & Masonry Products", "Aerosols", "Faux Finishing", "Paint & Coatings Calculator", "Deck Stains & Supplies", "Siding Stains", "Aerosols", "Concrete & Masonry Products", "Paint & Coatings Calculator", "Brushes", "Roller Covers, Frames & Accessories", "Tape & Masking", "Sandpaper & Abrasives", "Drop Cloths & Plastic Sheeting", "Caulks, Sealants & Caulking Tools", "Patching & Repair", "Painter's Tools", "Cleaning Supplies", "Safety Equipment", "Solvents & Removers", "Wallpaper Tools & Paste", "Drywall Compounds & Tools", "Painter's Wear", "Ladders, Scaffolds & Climbing Equipment", "Spray Equipment", "PVC DWV Pipe", "Brass Pipe", "CPVC Pipe", "Copper Pipe", "Galvanized Pipe", "PEX Pipe", "Polyethylene Pipe", "Sewer & Drain", "Specialty Pipe", "Vinyl Pipe & Tubing", "PVC Fittings", "CPVC Fittings", "Brass Fittings", "Copper Fittings", "Galvanized Fittings", "Black Iron Fittings", "Cast Iron Fittings", "PEX Fittings", "Polyethylene Fittings", "Specialty Fittings", "ABS DWV Fittings", " " }));
        ptypebox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ptypeboxActionPerformed(evt);
            }
        });
        getContentPane().add(ptypebox, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 59, 227, 33));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Product Type ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 66, -1, -1));

        xyz.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Product Type", "Product Name", "Product ID", "Manufacturer"
            }
        ));
        xyz.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                xyzMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(xyz);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 123, 1296, 280));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Product cost");

        qtybox.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        qtybox.setText("Please Select a Product");

        cpubox.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cpubox.setText("Please Select a Product");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Quantity");

        pnamebox.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        pnamebox.setText("Please Select a Product");

        manubox.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        manubox.setText("Please Select a Product");

        pidbox.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        pidbox.setText("Please Select a Product");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Product ID");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Product Name");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Manufacturer");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(qtybox, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 120, Short.MAX_VALUE)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cpubox, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pnamebox, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(manubox, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pidbox, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(qtybox, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cpubox, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(pidbox, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pnamebox, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(manubox, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 438, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("BALANCE STOCK VALUATION");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 10, -1, -1));

        jButton9.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton9.setText("Search");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(419, 57, 130, 36));

        jButton10.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton10.setText("Calculate Cost");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(626, 438, 138, 41));

        jButton11.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton11.setText("Clear");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(567, 57, 130, 36));

        jTable1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ProductType", "Total_Remaining_Quantity", "Total_Sum"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(626, 486, 712, 160));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/backgrnd1.png"))); // NOI18N
        jLabel15.setName(""); // NOI18N
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1366, 768));

        setSize(new java.awt.Dimension(1366, 768));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        v_InventoryHandlingMain a1 =new v_InventoryHandlingMain();
        a1.setVisible(true);
        this.dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void ptypeboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ptypeboxActionPerformed
        //SAME CODE FOR SERARCHING 
        String pt = ptypebox.getSelectedItem().toString();
        
        String sql="SELECT ProductID,ProductName,ProductType,Manufacture,Quantity,CostPerUnit FROM products WHERE "
                + "productType LIKE '"+pt+"' ";
         
        
        try{
            
        pst = con.prepareStatement(sql);
        rs = pst.executeQuery();
        xyz.setModel(DbUtils.resultSetToTableModel(rs));
        
        
        }catch(Exception e)
        {
            
        }
    }//GEN-LAST:event_ptypeboxActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        //search button
        
        String pt = ptypebox.getSelectedItem().toString();
        
        String sql="SELECT ProductID,ProductName,ProductType,Manufacture,Quantity,CostPerUnit FROM products WHERE "
                + "productType LIKE '"+pt+"' ";
         
        
        try{
            
        pst = con.prepareStatement(sql);
        rs = pst.executeQuery();
        xyz.setModel(DbUtils.resultSetToTableModel(rs));
        
        
        }catch(Exception e)
        {
            
        }
        
        
        
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // calculate cost button
       String pt = ptypebox.getSelectedItem().toString();
         
       try {
        //String sql="SELECT ProductID,ProductName,ProductType,Manufacture,Quantity,CostPerUnit FROM products ";
       // String sql="SELECT ProductType,Manufacture,(Quantity*CostPerUnit)as Total_Cost FROM products WHERE "
         //+ "productType LIKE '%"+pt+"%'";
         
         String sql="SELECT ProductType,sum(Quantity)as Total_Remaining_Quantity,sum(Quantity*CostPerUnit)as Total_sum FROM products WHERE "
         + "ProductType LIKE '%"+pt+"%'";
        
        pst = con.prepareStatement(sql);
        rs =pst.executeQuery();
        
        jTable1.setModel(DbUtils.resultSetToTableModel(rs));
        
        }
     catch (SQLException e)
        {
        }
       
        
        

    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        clear1();
        tableload();
        
    }//GEN-LAST:event_jButton11ActionPerformed

    private void xyzMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xyzMouseClicked
        // mouse click
        
         try{
        
        int row=xyz.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel)xyz.getModel();
        
        String pid= xyz.getValueAt(row, 0).toString();
        String pname= xyz.getValueAt(row, 1).toString();
        String manu= xyz.getValueAt(row, 3).toString();
        String qty= xyz.getValueAt(row, 4).toString();
        String cpu= xyz.getValueAt(row, 5).toString();
        
        qtybox.setText(qty);
        
        float x = new Float(qty);
        float y = new Float(cpu);
        
        float productcost =(x*y);
      
        cpubox.setText(String.valueOf(productcost));
        pidbox.setText(pid);
        pnamebox.setText(pname);
        manubox.setText(manu);
       
        }
        catch(Exception e)
        {
            
        }
    }//GEN-LAST:event_xyzMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(v_balance_stock_valuation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(v_balance_stock_valuation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(v_balance_stock_valuation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(v_balance_stock_valuation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new v_balance_stock_valuation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cpubox;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel manubox;
    private javax.swing.JLabel pidbox;
    private javax.swing.JLabel pnamebox;
    private javax.swing.JComboBox<String> ptypebox;
    private javax.swing.JLabel qtybox;
    private javax.swing.JTable xyz;
    // End of variables declaration//GEN-END:variables
}
